import { describe, expect, it } from 'vitest';
import { createDraftCalibration, isCalibrationOverdue, type CalibrationRecord } from '../../../src/modules/assets/calibration/domain/calibration.js';
import { TransitionCalibrationUseCase } from '../../../src/modules/assets/calibration/application/transition-calibration.js';
import type { CalibrationRepository } from '../../../src/modules/assets/calibration/ports/repository.js';
const ids = { actor: '00000000-0000-7000-8000-000000000001', equipment: '00000000-0000-7000-8000-000000000002', calibration: '00000000-0000-7000-8000-000000000003' };
const make = (): CalibrationRecord => createDraftCalibration({ id: ids.calibration, calibrationNo: 'CAL-001', equipmentId: ids.equipment, calibrationDate: new Date('2026-01-01T00:00:00Z'), dueDate: new Date('2026-02-01T00:00:00Z'), createdBy: ids.actor, now: new Date('2026-01-01T00:00:00Z') });
class FakeCalibrationRepository implements CalibrationRepository { value = make(); async create({ calibration }: { calibration: CalibrationRecord }) { this.value = calibration; return calibration; } async get() { return this.value; } async list() { return [this.value]; } async transition(input: any) { this.value = { ...this.value, state: input.action === 'SUBMIT' ? 'SUBMITTED' : input.action === 'APPROVE' ? 'APPROVED' : this.value.state, version: this.value.version + 1n }; return this.value; } }
const actor = (permission: string, id = ids.actor) => ({ id, accountState: 'ACTIVE' as const, roles: ['Supervisor'], permissions: [{ code: permission as never, scopes: ['GLOBAL' as const] }] });
describe('Assets calibration controls', () => {
  it('preserves the linked equipment and derives overdue only from a supplied due date', () => { const value = make(); expect(value.equipmentId).toBe(ids.equipment); expect(isCalibrationOverdue(value, new Date('2026-02-02T00:00:00Z'))).toBe(true); expect(isCalibrationOverdue({ dueDate: undefined }, new Date())).toBe(false); });
  it('allows submit but blocks current selection until policy is approved', async () => { const repo = new FakeCalibrationRepository(); const submit = new TransitionCalibrationUseCase(repo); const submitted = await submit.execute({ actor: actor('PERM-CAL-SUBMIT'), calibrationId: ids.calibration, expectedVersion: 1n, action: 'SUBMIT', requestId: 'req-3' }); expect(submitted.state).toBe('SUBMITTED'); await expect(submit.execute({ actor: actor('PERM-CAL-SUBMIT'), calibrationId: ids.calibration, expectedVersion: submitted.version, action: 'MAKE_CURRENT', requestId: 'req-4' })).rejects.toThrow(); });
  it('enforces separation of duties for approval', async () => { const repo = new FakeCalibrationRepository(); repo.value = { ...repo.value, state: 'SUBMITTED' }; const approve = new TransitionCalibrationUseCase(repo); await expect(approve.execute({ actor: actor('PERM-CAL-APPROVE'), calibrationId: ids.calibration, expectedVersion: 1n, action: 'APPROVE', requestId: 'req-5' })).rejects.toThrow(); });
});
