import { describe, expect, it } from 'vitest';
import { GetEquipmentEligibilityUseCase } from '../../../src/modules/assets/equipment/application/get-equipment-eligibility.js';
import type { ControlledContext, EquipmentContext } from '../../../src/modules/laboratory/domain/lab-test.js';
const actor = { id: '00000000-0000-7000-8000-000000000001', accountState: 'ACTIVE' as const, roles: [], permissions: [] };
const equipment = { id: '00000000-0000-7000-8000-000000000002', equipmentNo: 'EQ-1', name: 'Balance', state: 'ACTIVE' as const, createdBy: actor.id, createdAt: new Date(), updatedAt: new Date(), version: 1n };
const calibration = { id: '00000000-0000-7000-8000-000000000003', calibrationNo: 'CAL-1', equipmentId: equipment.id, state: 'CURRENT' as const, calibrationDate: new Date(), dueDate: new Date('2027-01-01T00:00:00Z'), createdAt: new Date(), createdBy: actor.id, updatedAt: new Date(), version: 1n };
const context: ControlledContext = { templateVersionId: 'tv', versionNo: '1', methodReference: 'method', sourceReference: 'source', contentHash: 'hash', parameters: [{ id: 'p', code: 'p', label: 'P', dataType: 'NUMERIC', unit: null, required: true, sourceReference: 'source', criteria: {} }], documents: [], equipment: [] , source: {}, requirementsReference: 'method' };
const usage: EquipmentContext = { equipmentId: equipment.id, calibrationRecordId: calibration.id, usedAt: new Date().toISOString(), equipmentSnapshot: { equipmentId: equipment.id }, calibrationSnapshot: { calibrationRecordId: calibration.id } };
describe('Assets-owned laboratory eligibility', () => { it('accepts an active equipment/current calibration pair', async () => { const useCase = new GetEquipmentEligibilityUseCase({ getEquipment: async () => equipment, getCalibration: async () => calibration }, () => new Date('2026-06-01T00:00:00Z')); await expect(useCase.verify({ actor, equipment: [usage], context })).resolves.toBeUndefined(); }); it('denies overdue use while policy is unresolved', async () => { const useCase = new GetEquipmentEligibilityUseCase({ getEquipment: async () => equipment, getCalibration: async () => ({ ...calibration, dueDate: new Date('2026-01-01T00:00:00Z') }) }, () => new Date('2026-06-01T00:00:00Z')); await expect(useCase.verify({ actor, equipment: [usage], context })).rejects.toThrow(); }); });
