#!/usr/bin/env python3
"""Offline, deterministic presentation of the 2026-10-04 read-only audit inventory.

Rows are evidence classifications, not assertions of successful runtime testing.
"""
from collections import Counter
import json
from html import escape
from pathlib import Path
from readiness_integrity import calculate, prompt_coverage
from requirement_links import LINKS
from unmapped_reconciliation_prompts import PROMPTS as UNMAPPED_PROMPTS
import re

ROOT = Path(__file__).resolve().parent
SHA = '6fc63e776614a333fb7f88854ce27d44fc196383'
STAMP = '2026-10-04T20:36:39Z'
WEIGHT = {'P0': 5, 'P1': 3, 'P2': 1}
VALUE = {'PASS': 1, 'PARTIAL': .5, 'FAIL': 0, 'BLOCKED': 0, 'NOT VERIFIED': 0}
ROWS = []

def add(ids, domain, evidence, status='NOT VERIFIED', level='E0', finding=None, fix=None, retest=None):
    for ident, title in ids:
        priority = 'P0' if ident.startswith('AUD-P0') else 'P2' if ident.startswith('AUD-P2') else 'P1'
        ROWS.append(dict(id=ident, title=title, domain=domain, priority=priority,
            status=status, level=level, evidence=evidence, finding=finding or 'No current end-to-end acceptance evidence for this item.',
            impact='Release claim cannot be accepted for this requirement.',
            fix=fix or 'Obtain candidate-bound controlled evidence; repair only reproduced defects.',
            retest=retest or 'Run positive and negative tests on an isolated PG18 candidate, then authorized runtime/UAT as applicable.'))

def pairs(prefix, names):
    return [(f'{prefix}-{i:03}', name) for i, name in enumerate(names, 1)]

p0 = ['End-to-end QC record journey','RBAC + SoD adversarial analysis','ALCOA+ integrity','Scientific calculation verification','Illegal state transition attack','Concurrent QC operations','Wrong-action prevention','Traceability drill','Evidence-to-claim consistency','Zero-trust UI tampering','Policy drift detection','Release readiness evidence gate']
add(pairs('AUD-P0', p0), 'QC workflow', 'Documents/UAT-ACCEPTANCE-PLAN.md:7-22; tests/e2e/critical-workflows.spec.ts; no candidate-bound authenticated run.', 'BLOCKED', 'E1', 'End-to-end populated role/state/record evidence was not executed.', 'Provide isolated PG18, role fixtures and an approved policy source; execute the specified journey and denial matrix.')
def revise(ident, **fields):
    row = next(r for r in ROWS if r['id'] == ident)
    row.update(fields)
revise('AUD-P0-004', level='E2', evidence='src/modules/laboratory/infrastructure/postgres-controlled-sources.ts:125-134; Documents/DECISION-ASSUMPTION-REGISTER-026.md:80-81', finding='Controlled evaluator throws; no approved source-bound positive decision criteria. PD-01/02/07 remain open.', fix='Obtain signed QC/QMS source/revision/units/limits first; keep fail-closed; verify exact decimal and boundaries.')
revise('AUD-P0-011', level='E2', evidence='Documents/STATE-MACHINES.md:3017-3093; src/modules/documents/application/approve-version.ts:5-14', finding='RD-019 / PD-13 / PD-32 remain unresolved; document approval is deliberately denied.', fix='Obtain Document Control/QMS decision; implement version-bound approved ceremony without bypass.')
revise('AUD-P0-012', level='E2', evidence='src/modules/release-governance/infrastructure/postgres-repository.ts:90-98; .github/workflows/ci.yml:145-212', finding='19-gate reconciliation returns false; no exact-SHA CI/provider/UAT/recovery proof.', fix='Approve gate mapping and collect exact candidate CI, schema, runtime, restore and signed UAT evidence.')
revise('AUD-P0-003', evidence='db/migrations/README.md:3-19; audit/2026-10-04/QC-POST-100-FINAL.md:24-38', finding='Protected-record immutability and correction chain not proven on current deployed database.')
revise('AUD-P0-009', evidence='audit/2026-10-04/QC-POST-100-FINAL.md:24-38; historical candidate only', finding='Historical local PASS and prior NO-GO cannot substantiate a current release claim.')

add(pairs('AUD-P1', ['Database forensic integrity','Audit trail completeness','Electronic signature verification','QC/lab exception analysis','Equipment eligibility','Controlled documents effectivity','Report provenance and export parity','Security attack surface','Data export leakage','Privacy and sensitive data']), 'Data / security', 'db/migrations/README.md:3-19; tests/integration; PostgreSQL18 current-candidate run not executed.', 'BLOCKED', 'E1')
revise('AUD-P1-003', level='E2', evidence='src/modules/documents/application/approve-version.ts:5-14; Documents/DECISION-ASSUMPTION-REGISTER-026.md:104', finding='Document-bound electronic-signature authority remains policy-blocked.')
revise('AUD-P1-006', evidence='Documents/STATE-MACHINES.md:3017-3093; Documents/QC_System_WI_SOP_Pack/References/READ-ME.txt:1-6', finding='D0.2 draft is not an approved/effective registered source.')
revise('AUD-P1-007', evidence='src/modules/reporting/application/report-snapshot.ts:6-23; export-report.ts:55-74', finding='Request-local digest exists; durable report-run provenance/retention not approved.', status='PARTIAL', level='E2')

ux = ['Operational reality','UX task completion','Time-to-complete benchmark','Clicks and keystrokes','Form friction','Navigation efficiency','Search and findability','Decision confidence','Dashboard clarity','Information density','Cognitive load','Visual hierarchy','Manager vs operator view','Progressive disclosure','Text reduction audit','Content compression score','Controlled content protection','Readability','Label and terminology consistency','Terminology compliance','UI consistency','Error message quality','Empty/loading/failure states','Confirmation and destructive actions','Failure recovery','Keyboard-first workflow','Human error simulation','Large data usability','Responsive usability','Accessibility WCAG 2.2 AA','Notification quality','Cross-module consistency','Evidence quality score','Ten-evidence audit drill']
add(pairs('AUD-UX', ux), 'UX', 'src/pages; Documents/ROUTE-ACCEPTANCE-MATRIX.md; no authenticated browser/participant measurements on this SHA.', 'NOT VERIFIED', 'E1', 'No measured authenticated page-task, keyboard, viewport or text inventory for this item.', 'Run page-by-page authorized task studies, count actions/words, preserve controlled wording, and retain screenshots plus machine-readable timings.')
revise('AUD-UX-017', evidence='Documents/QC_System_WI_SOP_Pack/References/READ-ME.txt:1-6', finding='Draft controlled material must not be shortened or represented as approved.', status='BLOCKED')
eng = ['Change impact','Regression risk map','Complexity hotspots','Maintainability','Dead feature/route','Architecture boundaries','Dependency supply chain','Configuration drift']
add(pairs('AUD-ENG', eng), 'Engineering', 'package.json:16-26; .github/workflows/ci.yml; targeted architecture check on current SHA.', 'NOT VERIFIED', 'E1')
revise('AUD-ENG-006', status='PARTIAL', level='E3', evidence='pnpm test:architecture exit 0 at 2026-10-04T20:35Z on HEAD; static boundary only.', finding='Static architectural boundary passes; runtime architecture and all dependency contracts not proven.')
add(pairs('AUD-OBS', ['Production observability','Data quality dashboard']), 'Observability', 'src/shared/observability/telemetry.ts:4-9,58-95; src/modules/system-health/infrastructure/postgres-health-probes.ts:86-154', 'PARTIAL', 'E2', 'No-op telemetry exporter and unrecorded worker heartbeat/delivery; production metrics unproven.', 'Approve privacy-safe exporter/worker/alert policy; prove delivery and failure detection on runtime.')
ops = ['Aging and bottlenecks','Workload balance','SLA/turnaround','Repeat failures','Near misses','Reject trends','NCR trends','Equipment downtime','Calibration risk','Closure rate','Approval delay','Data quality trend']
add(pairs('AUD-OPS', ops), 'Operational intelligence', 'src/modules/dashboard; no current populated record-based metric reconciliation or approved SLA on this candidate.', 'NOT VERIFIED', 'E1', 'Some read models exist; these particular metric numerators, grains, scope and source parity are unverified.', 'Define source-backed grain and window with owner; reconcile SQL, UI and authorized export on real records.')
p2 = ['Recovery integrity simulation','Performance under QC workload','Slow network/high latency','Human UAT','Role-based UAT','AI advisory safety','AI provider failure/fail-safe','Backup retention/restore','Release rollback simulation','Operational support readiness']
add(pairs('AUD-P2', p2), 'Reliability / validation', 'Documents/UAT-ACCEPTANCE-PLAN.md; Documents/BACKUP-RECOVERY-PLAN.md; no candidate-bound operator drill.', 'BLOCKED', 'E1', 'Required human/provider/load/recovery proof not performed for this candidate.', 'Use approved isolated target and human participants; never run destructive checks in production.')
revise('AUD-P2-006', status='PARTIAL', level='E2', evidence='src/modules/ai-advisory; audit/100-percent/ai-evals/results-2026-09-24.json (HISTORICAL/foreign SHA)', finding='Advisory-only source exists; live provider and current-model safety unverified.')

assert len(ROWS) == 88, len(ROWS)
assert len({r['id'] for r in ROWS}) == len(ROWS)
assert all(r['priority'] in WEIGHT and r['status'] in VALUE and r['evidence'] for r in ROWS)
assert all(r['status'] != 'PASS' or r['level'] in ('E3','E4','E5','E6') for r in ROWS)
calculate(ROWS)

def score(rows):
    try:
        num, den, percent = calculate(rows)
    except ValueError:
        return 'PERCENTAGE_INTEGRITY_ERROR'
    return f'{num:.1f}/{den} × 100 = {percent:.2f}%'

def tag(s): return '<code>' + escape(str(s)) + '</code>'
def cell(s): return '<td>' + escape(str(s)) + '</td>'
def table(headers, rows):
    return '<div class="scroll"><table><thead><tr>' + ''.join('<th scope="col">'+escape(h)+'</th>' for h in headers) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join(cell(v) for v in row)+'</tr>' for row in rows) + '</tbody></table></div>'
STYLE = '''<style>:root{color-scheme:light dark;font:16px/1.55 system-ui;--bg:#f4f6f6;--fg:#142831;--panel:#fff;--line:#b7c8cc;--accent:#155f68}@media(prefers-color-scheme:dark){:root{--bg:#101b20;--fg:#e5eff0;--panel:#192a30;--line:#4e656b;--accent:#80ced0}}body{margin:0;background:var(--bg);color:var(--fg)}main{max-width:1400px;margin:auto;padding:clamp(1rem,3vw,3rem)}h1{font-size:clamp(1.8rem,3vw,3rem);line-height:1.16}h2{margin-top:2.5rem;border-bottom:2px solid var(--accent)}a{color:var(--accent)}.card{background:var(--panel);border:1px solid var(--line);padding:1rem;margin:.6rem 0;border-radius:.4rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:.7rem}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;background:var(--panel);font-size:.86rem}th,td{border:1px solid var(--line);padding:.55rem;text-align:start;vertical-align:top;min-width:8rem}th{position:sticky;top:0;background:var(--panel)}code{overflow-wrap:anywhere}strong.alert{color:#b3432c}details{margin:.5rem 0;border:1px solid var(--line);padding:.75rem}summary{cursor:pointer;font-weight:700}@media print{body{background:white;color:black}main{max-width:none}.scroll{overflow:visible}table{font-size:8pt}th,td{min-width:0;break-inside:avoid}}</style>'''
def page(title, body): return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+escape(title)+'</title>'+STYLE+'</head><body><main>'+body+'</main></body></html>'

groups = [('Overall evidence-based', ROWS), *[(p+' closure', [r for r in ROWS if r['priority']==p]) for p in WEIGHT],
    *[(d+' readiness', [r for r in ROWS if r['domain']==d]) for d in dict.fromkeys(r['domain'] for r in ROWS)]]
other = ['Implementation coverage','Automated verification coverage','Runtime verification coverage','Human UAT coverage','Security readiness','Data integrity readiness','Scientific integrity readiness','Laboratory readiness','Authorization/SoD readiness','Audit/traceability readiness','Electronic signature readiness','Database readiness','Backup/recovery readiness','Accessibility readiness','Performance readiness','Controlled documents readiness','Reporting/export integrity readiness','Release governance readiness']
mapping = {'Security':['AUD-P0-002','AUD-P0-010','AUD-P1-008','AUD-P1-009','AUD-P1-010'], 'Data integrity':['AUD-P0-003','AUD-P0-006','AUD-P1-001','AUD-P1-002'], 'Scientific integrity':['AUD-P0-004','AUD-P0-007','AUD-P1-004'], 'Laboratory':['AUD-P0-001','AUD-P0-004','AUD-P1-004','AUD-P1-005'], 'Authorization/SoD':['AUD-P0-002','AUD-P0-010','AUD-P1-008'], 'Audit/traceability':['AUD-P0-003','AUD-P0-008','AUD-P1-002'], 'Electronic signature':['AUD-P1-003','AUD-P0-005'], 'Database':['AUD-P1-001','AUD-P0-006'], 'Backup/recovery':['AUD-P2-001','AUD-P2-008'], 'Accessibility':['AUD-UX-026','AUD-UX-029','AUD-UX-030'], 'Performance':['AUD-P2-002','AUD-P2-003','AUD-UX-028'], 'Controlled documents':['AUD-P0-011','AUD-P1-006','AUD-UX-017'], 'Reporting/export integrity':['AUD-P0-008','AUD-P1-007','AUD-P1-009'], 'Release governance':['AUD-P0-012','AUD-P2-009']}
groups += [(name+' readiness', [r for r in ROWS if r['id'] in ids]) for name,ids in mapping.items()]
groups += [('UX & operational efficiency', [r for r in ROWS if r['domain']=='UX']), ('Operational intelligence coverage',[r for r in ROWS if r['domain']=='Operational intelligence'])]
cards = [(name, score(rs), ', '.join(r['id'] for r in rs)) for name,rs in groups]
for name, minimum in [('Implementation coverage','E2'),('Automated verification coverage','E3'),('Runtime verification coverage','E5'),('Human UAT coverage','E6')]:
    levels = ['E0','E1','E2','E3','E4','E5','E6']
    num = sum(r['level'] in levels[levels.index(minimum):] for r in ROWS)
    cards.append((name, f'{num}/{len(ROWS)} × 100 = {num/len(ROWS)*100:.2f}%', ', '.join(r['id'] for r in ROWS)))

body = f'''<header><p>Read-only audit • candidate-bound classification • {STAMP}</p><h1>QC / Laboratory readiness — NO-GO</h1><p>Repository YEEEAE/QC-Operations-Laboratory-Management-System · main · SHA {tag(SHA)} · commit 2026-10-04T23:27:49+03:00 · clean at start. Application 0.1.0 · pnpm 11.25.0 · Node audited 24.20.0 for selected checks (default shell 22.22.3) · source migration 0045. Build ID, current CI run, deployed artifact, deployed DB head and runtime URL: NOT VERIFIED. Environment: local source only; no production DB audited.</p><p><strong class="alert">NOT READY:</strong> required scientific source, signed document policy, exact-candidate runtime/schema, human UAT and recovery remain unproven. A weighted number is not a release decision.</p></header>
<h2>Scorecards</h2><p>Weighted score = Σ(priority weight × status value) / Σ(applicable weights) × 100; P0=5, P1=3, P2=1; PASS=1, PARTIAL=.5, other states=0. No N/A applied. Coverage cards count evidence levels only, not successful requirements. All rows and denominators are listed below. Timestamp {STAMP}.</p><div class="grid">{''.join(f'<div class="card"><strong>{escape(n)}</strong><br>{escape(v)}</div>' for n,v,_ in cards)}</div><details><summary>Exact numerator, denominator and included IDs per card</summary>{table(['Metric','Calculation','Included IDs'],cards)}</details>
<h2>P0 blockers and production gate</h2><p>All 12 P0 items remain blocked pending candidate-bound runtime/authorized human evidence; scientific positive decision, document effectivity and 19-gate mapping have explicit fail-closed source boundaries. NO-GO irrespective of score. Gate checklist: P0 all PASS — NO; critical data/security risk excluded — NOT VERIFIED; approved science — NO; exact artifact/DB/CI/runtime parity — NOT VERIFIED; integration/E2E/UAT/restore — NOT VERIFIED; controlled claims — NOT VERIFIED.</p>
<h2>Evidence maturity and status</h2>{table(['Type','Counts'], [('Status',str(dict(Counter(r['status'] for r in ROWS)))),('Evidence level',str(dict(Counter(r['level'] for r in ROWS))))])}
<h2>Audit matrix — 88 fixed IDs</h2>{table(['ID','Domain','Priority','Test','Status','Evidence level','Score contribution','Evidence / freshness','Finding','Impact','Fix','Retest'],[(r['id'],r['domain'],r['priority'],r['title'],r['status'],r['level'],f"{WEIGHT[r['priority']]*VALUE[r['status']]:.1f}/{WEIGHT[r['priority']]}",r['evidence']+'; source CURRENT unless marked HISTORICAL; execution only when explicitly timestamped',r['finding'],r['impact'],r['fix'],r['retest']) for r in ROWS])}
<h2>Operational coverage and limits</h2><p>Receiving → inspection → laboratory → supervisor → QCM → release, reject/NCR/CAPA, documents, equipment/calibration/maintenance, tasks, reports and approvals: source paths exist, but no populated end-to-end acceptance on this SHA. Actor × route × action × state × scope × owner allow/deny matrix: NOT VERIFIED (no current authenticated fixture). Do not mistake a 200 default-deny page or invalid-input refusal for authorization evidence.</p>
<h2>UX page and text matrices</h2><p>Authenticated route-by-route page inventory and task timings, clicks, keystrokes, 320px/200% and manual AT: NOT VERIFIED. Source route registry is a planning inventory only; individual page scores and word-reduction percentages cannot be computed without rendered-state measurements. Controlled D0.2 wording: DO NOT AUTO-REDUCE.</p>{table(['Page family','Role','Clarity','Navigation','Task','Form','Text','Compression','Hierarchy','A11y','Responsive','Consistency','Recovery','Findability','Overall','Evidence'],[(name,'QC / Supervisor / QCM','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','src/pages; authenticated rendered-state audit absent') for name in ['Receiving','Inspection','Laboratory','Reject/NCR/CAPA','Documents','Equipment/Calibration/Maintenance','Tasks','Reports','Approvals','Dashboard']])}
<h2>Text reduction matrix</h2>{table(['Surface','Current words','Necessary words','Reduction potential','Duplicated text','Recommended copy','Controlled?'],[(name,'NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NOT VERIFIED','NONE — measurement required','YES — DO NOT AUTO-REDUCE' if name=='WI/SOP content' else 'NOT VERIFIED') for name in ['Dashboard','Receiving form','Laboratory form','Approval dialog','WI/SOP content']])}
<h2>Risks and top launch blockers</h2><p>Critical: unapproved scientific criteria, unsigned controlled document authority, unreconciled release gates. Very high: exact runtime/schema/CI/UAT/restore missing. High: no current server-side adversarial proof, protected-history DB privilege not re-read, export leakage untested. Likelihood NOT ASSESSED; severity here denotes potential impact, not observed exploit.</p>
<h2>What is verified / what is not</h2><p>Current local source checks: requirements guard PASS (100 rows, 80 domains), architecture PASS, 22/22 selected unit tests PASS, Astro typecheck 0 errors/114 hints on Node 24.20.0. These are narrow E3 observations, not 88 item PASS. Not verified: all current deployed/data-path decisions, 45-migration applied parity, exact-SHA CI, authenticated multi-role E2E, comprehensive security, accessibility, performance, signed UAT and provider restore. Historical provider 18/45 and earlier NO-GO are not today's applied schema.</p>
<h2>Evidence appendix</h2>{table(['Command/source','Result','Exit','Time UTC','SHA/environment'],[('git status --short --branch; git rev-parse HEAD','clean main; '+SHA,'0','2026-10-04T20:27Z',SHA+' local'),('pnpm requirements:check','100 requirements/80 domains PASS','0','2026-10-04T20:35Z',SHA+' Node24 local'),('pnpm test:architecture','boundary and route registry PASS','0','2026-10-04T20:35Z',SHA+' Node24 local'),('pnpm exec vitest run tests/unit/requirements/reconciliation-contract.test.ts tests/unit/ui/mutation-safety-contract.test.ts','22/22 PASS; 2 files','0','2026-10-04T20:36:39Z',SHA+' Node24 local'),('pnpm typecheck','0 errors, 0 warnings, 114 hints','0','2026-10-04T20:36Z',SHA+' Node24 local'),('Documents/QC_System_WI_SOP_Pack/References/READ-ME.txt','D0.2 DRAFT; 30 SOP, 68 WI; unsigned','read','2026-10-04',SHA+' local source')])}
<p>Evidence freshness: local source CURRENT relative to HEAD at audit start; prior packets HISTORICAL/FOREIGN SHA; production ENVIRONMENT MISMATCH until same candidate verified. Outputs are intentionally conservative; this is a partial execution audit, not certification.</p>'''

prompts = [
 ('0','Freeze candidate and collect environment evidence','AUD-P0-012','Inspect .github/workflows/ci.yml, db/migrations/README.md and release runbook. Obtain exact SHA CI run, signed artifact digest, deployed runtime identity and read-only applied-ledger/role read-back; compare all to one frozen candidate. Do not migrate or deploy. Fail if any identity diverges.','Exact SHA + artifact bytes + applied migration ledger + CI statuses are linked; mismatch remains NO-GO.','NONE'),
 ('1','Obtain scientific source and validate inspection/lab decisions','AUD-P0-004, AUD-P0-007','Inspect inspection postgres-repository.ts and laboratory/postgres-controlled-sources.ts. STOP until QC/QMS approves source ID, revision, units, exact decimal limits, rounding, retest semantics and effectivity. Then implement server-only evaluation and persisted source binding; test boundary values, missing source, stale revision and denial with zero writes.','Approved criteria and source hash drive reproducible PASS/FAIL; missing criteria denies, no inferred acceptance.','0'),
 ('2','Rehearse complete QC journey and concurrency','AUD-P0-001, AUD-P0-005, AUD-P0-006, AUD-P0-008','Inspect tests/integration/qc-100-final-013 and tests/e2e/critical-workflows.spec.ts. On isolated PG18, execute receiving→inspection→lab→both review stages→QCM→release/reject; assert actor/version/evidence/audit/report linkage. Run simultaneous approvals, stale versions and duplicate request replay with rollback checks.','One candidate-bound linked chain, all forbidden transitions denied without state/audit/signature mutation.','1'),
 ('3','Document control and signature ceremony','AUD-P0-011, AUD-P1-003, AUD-P1-006','Inspect documents/application/approve-version.ts and STATE-MACHINES.md. STOP for RD-019, PD-13 and PD-32 signed sources. Bind signer/intent/version/source digest/reauth to same transaction; verify approved ≠ effective and superseded history remains immutable.','Authorized signed approval exactly once; no effectivity without approved source; failure writes no partial signature.','1'),
 ('3','Role-state-scope adversarial suite','AUD-P0-002, AUD-P0-010, AUD-P1-008, AUD-P1-009','Inspect shared/authorization, policy registry and action routes. Build QC01/02/03, Supervisor, QCM, named owner and Admin fixture matrix with real records and positive controls. Tamper IDs, body, scope, role, owner and state; assert 403/404 and no state/audit/signature/export leakage.','QC01 approval denied server-side with unchanged row; QCM stage/version/scope allowed once; Admin-only owner path denied.','0'),
 ('4','Database ledger and protected history','AUD-P0-003, AUD-P1-001, AUD-P1-002','Inspect db/migrations and protected audit/signature DDL. Read production permissions only with authorization; use isolated PG18 for 45/45 clean/upgrade, FK/orphan and rollback tests. Reconcile least-privilege app role; no production privilege mutation without approval.','Applied ledger exact candidate head/checksums; protected records cannot UPDATE/DELETE/TRUNCATE by runtime role; correction append-only.','0'),
 ('5','Secure export and session boundaries','AUD-P1-008, AUD-P1-009, AUD-P1-010','Inspect reports export routes and tests/integration/security. Run authenticated cross-scope export/IDOR, CSRF, session expiry and sanitized error tests on isolated runtime; assert no unauthorized bytes or audit side effects.','Denied actor obtains no protected rows/metadata across UI, CSV and XLSX; positive control retains authorized access.','3,4'),
 ('6','Measure UX and copy before changing it','AUD-UX-002, AUD-UX-003, AUD-UX-004, AUD-UX-015, AUD-UX-016, AUD-UX-017','Inventory 86 registry routes plus 404/500, capture each relevant rendered state with authorized actors. Record time/clicks/keystrokes and exact UI words per page; mark controlled text and duplicates. Only propose shortened non-controlled wording with original, target counts and risk.','Per-page measured denominator, word sample and actor task evidence; controlled WI/SOP text never auto-reduced.','2,3'),
 ('7','Authenticated accessibility matrix','AUD-UX-026, AUD-UX-029, AUD-UX-030','On candidate build and allowed test data, run axe and manual keyboard/focus/VoiceOver or NVDA, 320px and 200% reflow, reduced motion. Retain route/persona/state-level failures and retests.','No critical keyboard or reflow blocker in required workflows; manual AT evidence signed and candidate-bound; no WCAG claim from axe alone.','6'),
 ('8','Provider recovery and load rehearsal','AUD-P2-001, AUD-P2-002, AUD-P2-008, AUD-P2-009','STOP until owner approves RPO/RTO, retention, isolated target and operator. Restore real candidate-matched backup into isolated target, reconcile rows/files/hashes. Load 40+ synthetic authorized users on disposable equivalent and report p50/p95/p99, throughput and error rate. Never destructive production test.','Recent restore digest and measured recovery with approved objectives; quantified load error budget; rollback plan approved.','0,4'),
 ('9','Operational metric lineage','AUD-OPS-001, AUD-OPS-003, AUD-OPS-006, AUD-OPS-012','Inspect dashboard read models. Agree metric grain, window and scope; compute SQL against real authorized records and reconcile dashboard/export independently; never fabricate SLA targets or missing data as zero.','Every displayed count reconciles to same filtered records and defined denominator/time window.','4'),
 ('10','Signed role-based UAT','AUD-P2-004, AUD-P2-005, AUD-UX-001','STOP for named authorized participants and approved scenario packet. Execute QC→Supervisor→QCM on exact candidate; capture observed outcomes, denial checks, defects/retest and actual participant signatures.','Required scenarios and roles completed and signed on same SHA/build/environment; blank templates are not acceptance.','2,7,8'),
 ('11','Release evidence reconciliation','AUD-P0-012, AUD-P0-009','Inspect release-governance postgres-repository.ts and RELEASE-RUNBOOK.md. STOP for approved 19-gate mapping and signer/provenance policy. Verify exact SHA CI/PG/E2E/UAT/restore and runtime artifact bytes; do not promote historical evidence or perform deploy.','All mandatory P0 PASS with exact-candidate source links and no blocked gate; otherwise NO-GO.','0,10')]
acquisition_ids = sorted({r['id'] for r in ROWS} - {ref for _, _, ids, *_ in prompts for ref in ids.split(', ')})
prompt_records = [dict(id=f'FIX-{index:02}', audit_ids=ids.split(', ')) for index, (_, _, ids, *_) in enumerate(prompts, 1)]
prompt_records += [dict(id=f'EVID-{ident}', audit_ids=[ident]) for ident in acquisition_ids]
coverage = prompt_coverage(ROWS, prompt_records)
assert not coverage['unknown'] and not coverage['duplicate_prompt_ids']
assert not coverage['unlinked']
requirements_source = (ROOT.parent/'Documents/REQUIREMENTS-RECONCILIATION.md').read_text(encoding='utf-8')
requirements = {match.group(1): {'rc_id': match.group(2), 'source': match.group(3),
    'capability': match.group(4), 'owning_task': match.group(5)}
    for line in requirements_source.splitlines()
    if (match := re.match(r'^\| (REQ-(?:AUTHZ|WFLOW|DINT|AUDF|RCOV|AIGV|READY|OPS|SCOPE)-\d{3}) \| (RC-\d{2}-\d{3}) \|.*?\| ([^|]+) \| [^|]+ \| [^|]+ \| (MANDATORY|OPTIONAL) \| ([^|]+) \|', line))}
assert len(requirements) == 100, len(requirements)
assert set(LINKS) <= {r['id'] for r in ROWS}
assert all(req in requirements for links in LINKS.values() for req in links)
assert set(UNMAPPED_PROMPTS) == ({r['id'] for r in ROWS} - set(LINKS))
ledger = {
    'audit_identity': {'git_sha': SHA, 'observed_at': STAMP, 'environment': 'local source only',
        'tree': 'clean at audit start; audit outputs subsequently changed working tree',
        'build_id': 'NOT VERIFIED', 'deployed_migration_head': 'NOT VERIFIED'},
    'denominator': {'items': len(ROWS), 'weighted': calculate(ROWS)[1],
        'note': '88-item partial audit inventory; distinct from approved 100/80/19/671 registers'},
    'coverage': coverage,
    'rows': [{**r, 'related_requirement_ids': list(LINKS.get(r['id'], ())),
        'mapping_status': 'CANDIDATE_LINK_NOT_ACCEPTANCE' if r['id'] in LINKS else 'NOT MAPPED',
        'requirement_register_refs': [requirements[req] for req in LINKS.get(r['id'], ())],
        'source_authority': 'REGISTER SOURCE REFERENCE ONLY — APPROVAL NOT VERIFIED' if r['id'] in LINKS else 'NOT VERIFIED',
        'owner': 'NOT VERIFIED — owning task is not a named authority',
        'evidence_freshness': 'CURRENT SOURCE ONLY' if r['level'] in ('E1','E2') else 'CURRENT LOCAL TEST ONLY' if r['level']=='E3' else 'NO CURRENT EVIDENCE',
        'evidence_environment': 'local source / selected local checks',
        'evidence_sha': SHA, 'evidence_observed_at': STAMP,
        'blocking_reason': r['finding'] if r['status']=='BLOCKED' else None,
        'next_action': 'ACQUIRE_EVIDENCE',
        'explicit_prompt_ids': [p['id'] for p in prompt_records if r['id'] in p['audit_ids']]}
        for r in ROWS],
}
(ROOT/'QC-READINESS-AUDIT-LEDGER.json').write_text(json.dumps(ledger, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
prompt_html = '<header><h1>Production readiness — execution playbook</h1><p>Derived from the 88-row conservative audit at '+SHA+'. Prompts specify evidence acquisition first; none authorizes production writes, commit or deploy. Current weighted score: '+score(ROWS)+'. Target for policy/human-dependent domains: MAX POSSIBLE UNTIL EXTERNAL EVIDENCE.</p></header>'
prompt_html += '<h2>Before / after tracking</h2>'+table(['Domain','Current %','Target','Blocking prompts','Verification needed'],[(n,v,'MAX POSSIBLE UNTIL EXTERNAL EVIDENCE','0–11','Recompute from exact candidate') for n,v,_ in cards if 'readiness' in n.lower()])
for index,(batch,title,ids,text,accept,dependency) in enumerate(prompts, 1):
    source = [r for r in ROWS if r['id'] in ids.split(', ')]
    prompt_html += f'<section class="card"><h2>Batch {batch} — {escape(title)}</h2><p><strong>Prompt ID:</strong> FIX-{index:02} · <strong>Source:</strong> {escape(ids)} · <strong>Severity:</strong> '+('Critical' if batch in '01234' else 'High')+f' · <strong>Current:</strong> {escape(score(source))} · <strong>Target:</strong> MAX POSSIBLE UNTIL EXTERNAL EVIDENCE · <strong>Dependency:</strong> {escape(dependency)}</p><p><strong>Evidence:</strong> {escape("; ".join(r["evidence"] for r in source))}</p><p><strong>Problem / root cause:</strong> {escape("; ".join(r["finding"] for r in source))} ROOT CAUSE TO BE VERIFIED unless explicitly established above.</p><p><strong>Goal and steps:</strong> {escape(text)}</p><p><strong>Automated + integration + E2E/security/UX tests:</strong> implement applicable positive and negative assertions above; run focused unit, isolated PostgreSQL18 integration and authenticated E2E, security and UX checks as relevant. Record commands, exit codes and exact SHA. Do not use production writes.</p><p><strong>Acceptance / required PASS evidence:</strong> {escape(accept)}</p><p><strong>Retest:</strong> {escape("; ".join(r["retest"] for r in source))} <code>pnpm test:unit</code>; <code>pnpm test:integration</code>; <code>pnpm verify:e2e:authenticated</code> as applicable on isolated candidate.</p><p><strong>Stop condition:</strong> unapproved scientific criteria, document/e-signature policy, provider authority, credential or human signature must be requested, never invented. <strong>Expected status:</strong> PARTIAL until complete independent evidence; PASS only after all acceptance conditions.</p></section>'
prompt_html += '<h2>Evidence-acquisition queue — no inferred repairs</h2><p>Each card below corresponds to an item not explicitly covered by the original thirteen tasks. It requests proof, not a code change. A repair task may be created only after a reproducible defect and its governing source are established.</p>'
for ident in acquisition_ids:
    row = next(r for r in ROWS if r['id']==ident)
    prompt_html += f'<section class="card"><h3>EVID-{escape(ident)} — {escape(row["title"])}</h3><p>Audit ID: {escape(ident)} · priority {row["priority"]} · current {row["status"]} / {row["level"]} · score {score([row])}. Evidence pointer: {escape(row["evidence"])}. Observed gap: {escape(row["finding"])}.</p><p>On a frozen candidate, inspect the referenced source and governing requirement; specify actor, record, state, scope, environment and measurable expected outcome before testing. Execute a positive control and a negative or failure case where relevant: {escape(row["retest"])} Retain command, exit code, timestamp, SHA/build, applied schema and sanitized result. Do not run destructive production tests or invent QC/SLA policy. If the prerequisite environment, authority or real data is unavailable, retain BLOCKED/NOT VERIFIED and name the blocker. If a defect is reproduced, open a separate root-cause remediation prompt with file paths and retest; otherwise do not edit code. Evidence required for PASS: candidate-bound result fulfilling the full audit test and human/operator sign-off when required.</p></section>'
prompt_html += '<h2 lang="ar" dir="rtl">مصالحة البنود الـ28 غير المرتبطة بمتطلب</h2><p lang="ar" dir="rtl">هذه مهام بحث وتوثيق، وليست أوامر لإضافة متطلبات أو تغيير حالة البنود. المصدر الحاكم يسبق الكود؛ أبقِ المقامات المعتمدة منفصلة.</p>'
for ident,(title,question,acceptance) in UNMAPPED_PROMPTS.items():
    row = next(r for r in ROWS if r['id']==ident)
    prompt_html += f'<section class="card" lang="ar" dir="rtl"><h3>MAP-{escape(ident)} — {escape(title)}</h3><p>Audit ID: {escape(ident)} · الأولوية {row["priority"]} · الحالة {escape(row["status"])} · الدرجة {score([row])}. <strong>الهدف:</strong> حسم علاقة المعيار بالمصدر دون رفع درجة الجاهزية.</p><p><strong>سؤال البحث:</strong> {escape(question)}</p><p><strong>التنفيذ:</strong> اقرأ Documents/REQUIREMENTS-TRACEABILITY.md وDocuments/REQUIREMENTS-RECONCILIATION.md والمصادر المذكورة؛ استخرج الفقرة والنسخة ومالك القرار. قارن النطاق والنية لا الكلمات المفتاحية وحدها. إذا لا يوجد مطلب مطابق، صنفه AUDIT-ONLY دون خلق معرّف متطلب. إذا المصدر متعارض أو غير معتمد فأبقِه BLOCKED_BY_AUTHORITY. لا تعدّل التطبيق أو سياسة QC أو المقامات 100/80/19/671.</p><p><strong>المخرج المطلوب:</strong> {escape(acceptance)} سجّل reference path:section، حالة DIRECT/RELATED/AUDIT-ONLY/BLOCKED_BY_AUTHORITY، SHA والوقت، ومالكًا مسمى أو NOT VERIFIED. اختبر سلبًا أن المطابقة لا تعتمد على كلمة مشتركة فقط؛ لا تغير status أو evidence level لمجرد نجاح المصالحة.</p><p><strong>شرط التوقف:</strong> غياب مصدر معتمد أو موافقة صاحب السلطة. حالة التدقيق المتوقعة تبقى {escape(row["status"])} حتى اختبار مستقل.</p></section>'
prompt_html += '<section class="card"><h2>FINAL-PRODUCTION-READINESS-RECONCILIATION</h2><p>Read-only. Re-run all 88 audit rows, freeze exact SHA, rerun required suites and verify applied DB migrations, artifact/runtime identity, complete role tests, human UAT and backup/restore. Recompute every numerator and denominator from raw rows, compare before and after, inspect all P0 and unresolved risks. Issue GO only after every release gate is evidenced; otherwise NO-GO. Never convert BLOCKED or historical results to PASS; do not repair code in this prompt.</p></section>'
from readiness_report_ar import render_arabic_report

report = render_arabic_report(ROWS, cards, score, SHA, STAMP, WEIGHT, VALUE, STYLE)
playbook = page('QC production execution prompts',prompt_html)
for filename, content in [('QC-ULTIMATE-EVIDENCE-BASED-READINESS-REPORT.html',report),('QC-PRODUCTION-READINESS-EXECUTION-PROMPTS.html',playbook)]:
    (ROOT/filename).write_text(content, encoding='utf-8')
print('rows',len(ROWS),'score',score(ROWS),'status',dict(Counter(r['status'] for r in ROWS)))
