import { describe, expect, it } from 'vitest';
import { CreateReceivingUseCase } from '../../../src/modules/quarantine/receiving/application/create-receiving.js';
import { TransitionReceivingUseCase } from '../../../src/modules/quarantine/receiving/application/transition-receiving.js';
import type { ReceivingRepository } from '../../../src/modules/quarantine/receiving/ports/repository.js';
import type { ReceivingItem } from '../../../src/modules/quarantine/receiving/domain/receiving-item.js';
import type { ActorContext } from '../../../src/shared/authorization/types.js';
const actor:ActorContext={id:'01900000-0000-7000-8000-000000000001',accountState:'ACTIVE',roles:['SUPERVISOR'],permissions:[{code:'PERM-QUAR-CREATE',scopes:['OWN']},{code:'PERM-QUAR-EDIT',scopes:['OWN']},{code:'PERM-QUAR-START-INSPECTION',scopes:['OWN']},{code:'PERM-QUAR-HOLD',scopes:['OWN']}]};
function repo(){let item:ReceivingItem|undefined;return {async create(i:any){item=i.item;return item},async get(){return item},async list(){return item?[item]:[]},async updateDraft(){return item!},async transition(i:any){item={...item!,workflowState:i.action==='START_INSPECTION'?'UNDER_INSPECTION':'HOLD',version:item!.version+1n};return item}} as unknown as ReceivingRepository;}
describe('quarantine receiving use cases',()=>{it('creates separate workflow, result, and release facts',async()=>{const r=repo();const x=await new CreateReceivingUseCase(r,()=>new Date('2026-01-01')).execute({actor,receivingNo:'RCV-1',docNo:'DOC-1',itemCode:'ITEM-1',description:'Material',lot:'LOT-1',qty:'2',receivingDate:new Date('2026-01-01'),requestId:'req'});expect(x.workflowState).toBe('PENDING');expect(x.inspectionResult).toBe('NOT_STARTED');expect(x.releaseSystem).toBe(false);});it('never accepts arbitrary target state and enforces permission',async()=>{const r=repo();await new CreateReceivingUseCase(r).execute({actor,receivingNo:'RCV-2',docNo:'DOC-1',itemCode:'ITEM-1',description:'Material',lot:'LOT-1',qty:'2',receivingDate:new Date(),requestId:'req'});await expect(new TransitionReceivingUseCase(r).execute({actor,id:'01900000-0000-7000-8000-000000000002',expectedVersion:1n,action:'START_INSPECTION',requestId:'req'})).rejects.toThrow();});});
