import { createHash } from 'node:crypto';
import type { Kysely,Transaction } from 'kysely';
import type { DatabaseSchema } from '../../../shared/database/db-types.js';
import { AppError } from '../../../shared/errors/app-error.js';
import { uuidv7 } from '../../../shared/id/uuid.js';
import type { ActorContext } from '../../../shared/authorization/types.js';
import { actorHasScope } from '../../../shared/authorization/scope-evaluator.js';
import type { AuditRepository } from '../../../shared/audit/audit-repository.js'; import { PostgresAuditRepository } from '../../../shared/audit/postgres-audit-repository.js';
import type { OutboxRepository } from '../../../shared/outbox/outbox-repository.js'; import { stableJson } from '../../../shared/json/stable-stringify.js'; import { PostgresOutboxRepository } from '../../../shared/outbox/postgres-outbox-repository.js';
import type { LabRepository,Mutation } from '../ports/repository.js'; import type { ControlledContext,LabTest } from '../domain/lab-test.js';
const hash=(value:unknown)=>createHash('sha256').update(stableJson(value)).digest('hex');
export class PostgresLabRepository implements LabRepository {
 constructor(private readonly db:Kysely<DatabaseSchema>,private readonly audit?:AuditRepository,private readonly outbox?:OutboxRepository){}
 async get(id:string,actor:ActorContext){const row=await this.db.selectFrom('lab_tests').selectAll().where('id','=',id).executeTakeFirst();if(!row)return undefined;if(!actorHasScope(actor,{type:'LAB_TEST',id,state:row.state,authorId:row.author_id},{ownerId:row.author_id},actor.permissions.find(p=>p.code==='PERM-LAB-VIEW')))return undefined;const [parameters,samples,measurements,snapshot]=await Promise.all([this.db.selectFrom('lab_test_template_parameters').selectAll().where('template_version_id','=',row.template_version_id).execute(),this.db.selectFrom('lab_samples').selectAll().where('lab_test_id','=',id).execute(),this.db.selectFrom('lab_measurements').selectAll().where('lab_test_id','=',id).execute(),this.db.selectFrom('lab_test_snapshots').selectAll().where('lab_test_id','=',id).orderBy('snapshot_version','desc').executeTakeFirst()]);const ctx=snapshot?.template_snapshot as {test:LabTest;context:ControlledContext}|undefined;if(!ctx?.test||!ctx?.context)throw new AppError('SYSTEM_DATABASE_UNAVAILABLE');return {...(ctx.test as unknown as Omit<LabTest,'samples'|'measurements'|'version'|'state'|'scientificResult'>),id,state:row.state as LabTest['state'],scientificResult:row.scientific_result as LabTest['scientificResult'],version:BigInt(row.version),samples:samples.map(s=>({id:s.id,identifier:s.sample_identifier})),measurements:measurements.map(m=>({id:m.id,sampleId:m.sample_id!,parameterId:m.template_parameter_id,raw:m.raw_numeric_value??m.raw_text_value??m.raw_boolean_value!,unit:m.unit,remarks:m.remarks??undefined,enteredBy:m.entered_by,enteredAt:m.entered_at.toISOString()})),context:{...ctx.context,parameters:parameters.map(p=>({id:p.id,code:p.parameter_code,label:p.label,dataType:p.data_type as 'NUMERIC'|'TEXT'|'BOOLEAN',unit:p.unit,required:p.required,sourceReference:p.controlled_source_reference??'',criteria:(p.acceptance_rule_payload??{}) as Readonly<Record<string,unknown>>}))}};}
 async list(actor:ActorContext){const rows=await this.db.selectFrom('lab_tests').select('id').orderBy('updated_at','desc').execute();const output:LabTest[]=[];for(const row of rows){const test=await this.get(row.id,actor);if(test)output.push(test);}return output;}
 async create(test:LabTest,mutation:Mutation){return this.persist(undefined,test,mutation);}
 async save(previous:LabTest,next:LabTest,mutation:Mutation){return this.persist(previous,next,mutation);}
 async history(id:string,actor:ActorContext){await this.get(id,actor);const rows=await this.db.selectFrom('lab_test_snapshots').selectAll().where('lab_test_id','=',id).orderBy('snapshot_version').execute();return rows.map(r=>({stage:r.snapshot_stage,hash:r.snapshot_hash,record:r.template_snapshot as LabTest}));}
 private async persist(previous:LabTest|undefined,next:LabTest,mutation:Mutation){return this.db.transaction().execute(async tx=>{if(!previous)await tx.insertInto('lab_tests').values({id:next.id,lab_test_no:next.labTestNo,template_version_id:next.context.templateVersionId,state:next.state,scientific_result:null,source_receiving_item_id:null,original_test_id:next.originalTestId,retest_sequence:next.retestSequence,retest_reason:next.retestReason,author_id:next.authorId,submitted_at:null,review_started_at:null,approved_at:null,rejected_at:null,voided_at:null,void_reason:null,snapshot_id:null,created_by:next.createdBy,updated_by:next.authorId,updated_at:new Date(next.updatedAt),version:next.version}).execute();else {const changed=await tx.updateTable('lab_tests').set({state:next.state,scientific_result:next.scientificResult,submitted_at:next.submittedAt?new Date(next.submittedAt):null,review_started_at:next.reviewStartedAt?new Date(next.reviewStartedAt):null,approved_at:next.approvedAt?new Date(next.approvedAt):null,updated_by:mutation.actor.id,updated_at:new Date(next.updatedAt),version:next.version}).where('id','=',next.id).where('version','=',previous.version).where('state','=',previous.state).executeTakeFirst();if(!changed.numUpdatedRows)throw new AppError('CONFLICT_STALE_VERSION',{userSafe:true});await tx.deleteFrom('lab_measurements').where('lab_test_id','=',next.id).execute();}
 if(previous){await tx.deleteFrom('lab_samples').where('lab_test_id','=',next.id).execute();} if(next.samples.length)await tx.insertInto('lab_samples').values(next.samples.map((s,index)=>({id:s.id,lab_test_id:next.id,sample_no:null,sample_identifier:s.identifier,position:index, sample_source:null,state:null,created_by:next.createdBy,version:1n}))).execute(); if(next.measurements.length)await tx.insertInto('lab_measurements').values(next.measurements.map(m=>({id:m.id,lab_test_id:next.id,sample_id:m.sampleId,template_parameter_id:m.parameterId,raw_numeric_value:typeof m.raw==='string'&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(m.raw)?m.raw:null,raw_text_value:typeof m.raw==='string'&&!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(m.raw)?m.raw:null,raw_boolean_value:typeof m.raw==='boolean'?m.raw:null,unit:m.unit,calculated_value:null,calculated_unit:null,result:null,remarks:m.remarks??null,entered_by:m.enteredBy,entered_at:new Date(m.enteredAt),updated_at:new Date(m.enteredAt),version:1n}))).execute();
 const snapshot={test:next,context:next.context};const snap=await tx.insertInto('lab_test_snapshots').values({id:uuidv7(),lab_test_id:next.id,snapshot_version:Number(next.version),snapshot_stage:mutation.action,template_snapshot:stableJson(snapshot),source_snapshot:stableJson(next.context.source),equipment_snapshot:stableJson(next.context.equipment),calibration_snapshot:stableJson(next.context.equipment.map(e=>e.calibrationSnapshot)),document_snapshot:stableJson(next.context.documents),criteria_snapshot:stableJson(next.context.parameters.map(p=>p.criteria)),sample_context_snapshot:stableJson(next.samples),created_at:new Date(),snapshot_hash:hash(snapshot)}).returningAll().executeTakeFirstOrThrow();await tx.updateTable('lab_tests').set({snapshot_id:snap.id}).where('id','=',next.id).execute();await this.auditFor(tx)?.append({actorType:'USER',actorId:mutation.actor.id,subjectType:'LAB_TEST',subjectId:next.id,action:mutation.action,oldState:previous?.state,newState:next.state,reason:mutation.reason,requestId:mutation.requestId});await this.outboxFor(tx)?.enqueue({eventType:'LAB_TEST_CHANGED',aggregateType:'LAB_TEST',aggregateId:next.id,payload:{action:mutation.action,state:next.state},dedupeKey:`lab:${next.id}:v${next.version}`});return next;});}
 private auditFor(tx:Transaction<DatabaseSchema>){return this.audit instanceof PostgresAuditRepository?new PostgresAuditRepository(tx):this.audit;} private outboxFor(tx:Transaction<DatabaseSchema>){return this.outbox instanceof PostgresOutboxRepository?new PostgresOutboxRepository(tx):this.outbox;}
}
