import { defineAction,ActionError } from 'astro:actions'; import { z } from 'astro:schema'; import { AppError } from '../shared/errors/app-error.js'; import { laboratoryActionDependencies } from '../modules/laboratory/application/dependencies.js';
const actor=(context:{locals:App.Locals})=>{if(!context.locals.actor)throw new AppError('AUTH_REQUIRED',{userSafe:true});return context.locals.actor;}; const requestId=(context:{locals:App.Locals})=>context.locals.requestContext?.requestId??'unknown'; const id=z.object({id:z.string().uuid(),expectedVersion:z.coerce.bigint()});
async function run<T>(work:()=>Promise<T>){try{return await work();}catch(error){throw new ActionError({code:error instanceof AppError&&error.category==='AUTHORIZATION'?'FORBIDDEN':'BAD_REQUEST',message:'Unable to complete the controlled laboratory action.'});}}
const create=defineAction({accept:'json',input:z.object({templateVersionId:z.string().uuid(),labTestNo:z.string().trim().min(1)}),handler:(input,context)=>run(()=>laboratoryActionDependencies().create.execute({...input,actor:actor(context),requestId:requestId(context)}))});
const saveMeasurements=defineAction({accept:'json',input:id.extend({samples:z.array(z.object({id:z.string().uuid(),identifier:z.string().trim().min(1)})).min(1),measurements:z.array(z.object({sampleId:z.string().uuid(),parameterId:z.string().uuid(),raw:z.union([z.string(),z.boolean()]),unit:z.string().nullable(),remarks:z.string().optional()}))}),handler:(input,context)=>run(()=>laboratoryActionDependencies().saveMeasurements.execute({...input,actor:actor(context),requestId:requestId(context)}))});
const submit=defineAction({accept:'json',input:id,handler:(input,context)=>run(()=>laboratoryActionDependencies().submit.execute({...input,actor:actor(context),requestId:requestId(context)}))});
const review=defineAction({accept:'json',input:id,handler:(input,context)=>run(()=>laboratoryActionDependencies().review.execute({...input,actor:actor(context),requestId:requestId(context)}))});
const returnTest=defineAction({accept:'json',input:id.extend({reason:z.string().trim().min(1)}),handler:(input,context)=>run(()=>laboratoryActionDependencies().return.execute({...input,actor:actor(context),requestId:requestId(context)}))});
const resume=defineAction({accept:'json',input:id,handler:(input,context)=>run(()=>laboratoryActionDependencies().resume.execute({...input,actor:actor(context),requestId:requestId(context)}))});
const approve=defineAction({accept:'json',input:id,handler:(input,context)=>run(()=>laboratoryActionDependencies().approve.execute({...input,actor:actor(context),requestId:requestId(context)}))});
const createRetest=defineAction({accept:'json',input:z.object({originalId:z.string().uuid(),reason:z.string().trim().min(1)}),handler:(input,context)=>run(()=>laboratoryActionDependencies().retest.execute({...input,actor:actor(context),requestId:requestId(context)}))});
export const laboratory={create,saveMeasurements,submit,review,returnTest,resume,approve,createRetest};
