import type { Kysely } from 'kysely';
import type { DatabaseSchema, DatabaseRow } from '../../../../shared/database/db-types.js';
import { translateDatabaseError } from '../../../../shared/database/database.js';
import { AppError } from '../../../../shared/errors/app-error.js';
import { actorHasScope } from '../../../../shared/authorization/scope-evaluator.js';
import { uuidv7 } from '../../../../shared/id/uuid.js';
import type { ActorContext } from '../../../../shared/authorization/types.js';
import type { InspectionRepository } from '../ports/repository.js';
import type { Inspection } from '../domain/inspection.js';

const map = (r: DatabaseRow<'inspection_reports'>, rec: DatabaseRow<'receiving_items'>, tv: DatabaseRow<'inspection_template_versions'>): Inspection => ({
  id:r.id, inspectionNo:r.inspection_no,
  receiving:{receivingId:rec.id,receivingNo:rec.receiving_no,docNo:rec.doc_no,itemCode:rec.item_code,description:rec.description,lot:rec.lot,qty:String(rec.qty),receivingDate:new Date(rec.receiving_date),expiryDate:rec.expiry_date?new Date(rec.expiry_date):undefined},
  template:{templateId:tv.template_id,templateVersionId:tv.id,versionNo:tv.version_no,templateSnapshot:{templateVersionId:tv.id,versionNo:tv.version_no},approved:tv.state==='APPROVED'},
  state:r.state as Inspection['state'], finalResult:r.final_result as Inspection['finalResult'], authorId:r.author_id, results:[], submittedAt:r.submitted_at??undefined, version:BigInt(r.version), createdAt:r.created_at, updatedAt:r.updated_at,
});
export class PostgresInspectionRepository implements InspectionRepository {
  constructor(private readonly db:Kysely<DatabaseSchema>) {}
  private async load(id:string){const r=await this.db.selectFrom('inspection_reports').selectAll().where('id','=',id).executeTakeFirst();if(!r)return;const rec=await this.db.selectFrom('receiving_items').selectAll().where('id','=',r.receiving_item_id).executeTakeFirstOrThrow();const tv=await this.db.selectFrom('inspection_template_versions').selectAll().where('id','=',r.template_version_id).executeTakeFirstOrThrow();return map(r,rec,tv);}
  async get(id:string,actor:ActorContext){const x=await this.load(id);return x&&actorHasScope(actor,{type:'INSPECTION_REPORT',id:x.id,state:x.state,authorId:x.authorId,executorId:x.authorId},{ownerId:x.authorId,assigneeId:x.authorId})?x:undefined;}
  async list(i:any){const rows=await this.db.selectFrom('inspection_reports').select('id').orderBy('updated_at','desc').execute();const out:Inspection[]=[];for(const r of rows){const x=await this.get(r.id,i.actor);if(x&&(!i.state||x.state===i.state)&&(!i.assignedTo||x.authorId===i.assignedTo))out.push(x);}return out;}
  async create(i:any){try{const x=i.inspection;await this.db.insertInto('inspection_reports').values({id:x.id,inspection_no:x.inspectionNo,receiving_item_id:x.receiving.receivingId,template_version_id:x.template.templateVersionId,state:'DRAFT',final_result:null,author_id:x.authorId,submitted_at:null,review_started_at:null,approved_at:null,rejected_at:null,voided_at:null,void_reason:null,snapshot_id:null,created_by:x.authorId,updated_by:x.authorId,updated_at:x.updatedAt,version:1n}).execute();return x;}catch(e){throw translateDatabaseError(e);}}
  async saveDraft(i:any){const r=await this.db.updateTable('inspection_reports').set({final_result:i.finalResult??null,updated_by:i.actor.id,updated_at:new Date(),version:i.expectedVersion+1n}).where('id','=',i.id).where('version','=',i.expectedVersion).where('state','=','DRAFT').returningAll().executeTakeFirst();if(!r)throw new AppError('CONFLICT_STALE_VERSION',{userSafe:true});return this.load(i.id) as Promise<Inspection>;}
  async transition(i:any){const x=await this.get(i.id,i.actor);if(!x)throw new AppError('RESOURCE_NOT_FOUND',{userSafe:true});const next=i.action==='SUBMIT'?'SUBMITTED':i.action==='RESUME'?'DRAFT':x.state;try{return await this.db.transaction().execute(async tx=>{const r=await tx.updateTable('inspection_reports').set({state:next,submitted_at:i.action==='SUBMIT'?new Date():x.submittedAt,updated_by:i.actor.id,updated_at:new Date(),version:i.expectedVersion+1n}).where('id','=',i.id).where('version','=',i.expectedVersion).where('state','=',x.state).returningAll().executeTakeFirst();if(!r)throw new AppError('CONFLICT_STALE_VERSION',{userSafe:true});if(i.action==='SUBMIT'){const s=await tx.insertInto('inspection_report_snapshots').values({id:uuidv7(),inspection_report_id:i.id,snapshot_version:Number(i.expectedVersion),snapshot_stage:'SUBMISSION',receiving_snapshot:x.receiving,template_snapshot:x.template.templateSnapshot,controlled_source_snapshot:null,criteria_snapshot:null,created_at:new Date(),snapshot_hash:`inspection:${i.id}:v${i.expectedVersion}`}).returningAll().executeTakeFirstOrThrow();await tx.updateTable('inspection_reports').set({snapshot_id:s.id}).where('id','=',i.id).execute();}return {...x,state:next,version:BigInt(r.version)} as Inspection;});}catch(e){if(e instanceof AppError)throw e;throw translateDatabaseError(e);}}
}
