import { getDatabase } from '../../../shared/database/database.js';
import { PostgresAuditRepository } from '../../../shared/audit/postgres-audit-repository.js';
import { PostgresOutboxRepository } from '../../../shared/outbox/postgres-outbox-repository.js';
import { PostgresEquipmentRepository } from '../equipment/infrastructure/postgres-repository.js';
import { PostgresCalibrationRepository } from '../calibration/infrastructure/postgres-repository.js';
import { PostgresMaintenanceRepository } from '../maintenance/infrastructure/postgres-repository.js';
import { PostgresEquipmentEligibilityReader } from '../equipment/infrastructure/eligibility-reader.js';
import { CreateEquipmentUseCase } from '../equipment/application/create-equipment.js'; import { GetEquipmentUseCase } from '../equipment/application/get-equipment.js'; import { ListEquipmentUseCase } from '../equipment/application/list-equipment.js'; import { UpdateEquipmentUseCase } from '../equipment/application/update-equipment.js';
import { CreateCalibrationUseCase } from '../calibration/application/create-calibration.js'; import { GetCalibrationUseCase } from '../calibration/application/get-calibration.js'; import { ListCalibrationsUseCase } from '../calibration/application/list-calibrations.js'; import { TransitionCalibrationUseCase } from '../calibration/application/transition-calibration.js';
import { CreateMaintenanceUseCase } from '../maintenance/application/create-maintenance.js'; import { GetMaintenanceUseCase } from '../maintenance/application/get-maintenance.js'; import { ListMaintenanceUseCase } from '../maintenance/application/list-maintenance.js'; import { TransitionMaintenanceUseCase } from '../maintenance/application/transition-maintenance.js';
import { GetEquipmentEligibilityUseCase } from '../equipment/application/get-equipment-eligibility.js';
const read = () => { const db = getDatabase(); return { equipment: new PostgresEquipmentRepository(db), calibration: new PostgresCalibrationRepository(db), maintenance: new PostgresMaintenanceRepository(db) }; };
export function assetsReadDependencies() { const repositories = read(); return { equipment: { get: new GetEquipmentUseCase(repositories.equipment), list: new ListEquipmentUseCase(repositories.equipment) }, calibration: { get: new GetCalibrationUseCase(repositories.calibration), list: new ListCalibrationsUseCase(repositories.calibration) }, maintenance: { get: new GetMaintenanceUseCase(repositories.maintenance), list: new ListMaintenanceUseCase(repositories.maintenance) } }; }
export function assetsActionDependencies() { const db = getDatabase(); const audit = new PostgresAuditRepository(db); const outbox = new PostgresOutboxRepository(db); const equipment = new PostgresEquipmentRepository(db, audit, outbox); const calibration = new PostgresCalibrationRepository(db, audit, outbox); const maintenance = new PostgresMaintenanceRepository(db, audit, outbox); return { equipment: { create: new CreateEquipmentUseCase(equipment), update: new UpdateEquipmentUseCase(equipment) }, calibration: { create: new CreateCalibrationUseCase(calibration), transition: new TransitionCalibrationUseCase(calibration) }, maintenance: { create: new CreateMaintenanceUseCase(maintenance), transition: new TransitionMaintenanceUseCase(maintenance) } }; }
export function assetsEligibilityDependencies() { const db = getDatabase(); return new GetEquipmentEligibilityUseCase(new PostgresEquipmentEligibilityReader(db)); }
