import type { ReportColumn } from '../domain/report-definition.js';
import type { ReportRow } from '../ports/report-query.js';

export function sanitizeSpreadsheetCell(value: string): string {
  // Spreadsheet applications may ignore leading whitespace/control characters
  // before interpreting a formula. Inspect the first meaningful code point,
  // but retain the original value after the protective apostrophe.
  for (const character of value) {
    const codePoint = character.codePointAt(0)!;
    if (
      /\s/u.test(character) ||
      codePoint <= 0x1f ||
      (codePoint >= 0x7f && codePoint <= 0x9f) ||
      codePoint === 0xfeff
    )
      continue;
    return '=+-@'.includes(character) ? `'${value}` : value;
  }
  return value;
}
function cell(value: unknown): string {
  const safe = sanitizeSpreadsheetCell(value === null || value === undefined ? '' : String(value));
  return /[",\r\n]/.test(safe) ? `"${safe.replaceAll('"', '""')}"` : safe;
}
export interface ReportExportMetadata {
  readonly report: string;
  readonly generatedAt: string;
  readonly generatedBy: string;
  readonly scope: string;
  readonly period: string;
  readonly filters: string;
  readonly count: number;
  readonly status: string;
  readonly source: string;
}

export function toCsv(
  rows: readonly ReportRow[],
  columns: readonly ReportColumn[],
  metadata?: ReportExportMetadata,
): string {
  const header = columns.map((column) => cell(column.label)).join(',');
  const metadataRows = metadata
    ? [
        ['Report', metadata.report],
        ['Generated at (UTC)', metadata.generatedAt],
        ['Generated by', metadata.generatedBy],
        ['Actor scope', metadata.scope],
        ['Period', metadata.period],
        ['Filters', metadata.filters],
        ['Record count', `${metadata.count} records`],
        ['Status', metadata.status],
        ['Source', metadata.source],
        [],
      ].map((row) => row.map(cell).join(','))
    : [];
  return (
    '\ufeff' +
    [
      ...metadataRows,
      header,
      ...rows.map((row) => columns.map((column) => cell(row[column.key])).join(',')),
    ].join('\r\n') +
    '\r\n'
  );
}
export function csvBytes(
  rows: readonly ReportRow[],
  columns: readonly ReportColumn[],
  metadata?: ReportExportMetadata,
): Buffer {
  return Buffer.from(toCsv(rows, columns, metadata), 'utf8');
}
