import type { Kysely } from 'kysely';
import type { DatabaseSchema } from '../../../../shared/database/db-types.js';
import type { CalibrationRecord } from '../../calibration/domain/calibration.js';
import type { Equipment } from '../domain/equipment.js';
import type { EquipmentEligibilityReader } from '../application/get-equipment-eligibility.js';
export class PostgresEquipmentEligibilityReader implements EquipmentEligibilityReader {
  constructor(private readonly db: Kysely<DatabaseSchema>) {}
  async getEquipment(id: string): Promise<Equipment | undefined> { const row = await this.db.selectFrom('equipment').selectAll().where('id', '=', id).executeTakeFirst(); return row ? { id: row.id, equipmentNo: row.equipment_no, name: row.name, manufacturer: row.manufacturer ?? undefined, model: row.model ?? undefined, serialNo: row.serial_no ?? undefined, location: row.location ?? undefined, state: row.state as Equipment['state'], currentCalibrationId: row.current_calibration_id ?? undefined, commissionedAt: row.commissioned_at ?? undefined, decommissionedAt: row.decommissioned_at ?? undefined, createdBy: row.created_by, createdAt: row.created_at, updatedBy: row.updated_by ?? undefined, updatedAt: row.updated_at, version: BigInt(row.version) } : undefined; }
  async getCalibration(id: string): Promise<CalibrationRecord | undefined> { const row = await this.db.selectFrom('calibration_records').selectAll().where('id', '=', id).executeTakeFirst(); return row ? { id: row.id, calibrationNo: row.calibration_no, equipmentId: row.equipment_id, state: row.state as CalibrationRecord['state'], calibrationDate: new Date(`${row.calibration_date}T00:00:00.000Z`), dueDate: row.due_date ? new Date(`${row.due_date}T00:00:00.000Z`) : undefined, provider: row.provider ?? undefined, certificateNo: row.certificate_no ?? undefined, result: row.result ?? undefined, approvedAt: row.approved_at ?? undefined, approvedBy: row.approved_by ?? undefined, becameCurrentAt: row.became_current_at ?? undefined, supersededAt: row.superseded_at ?? undefined, voidedAt: row.voided_at ?? undefined, voidReason: row.void_reason ?? undefined, createdAt: row.created_at, createdBy: row.created_by, updatedAt: row.updated_at, version: BigInt(row.version) } : undefined; }
}
