import type { PermissionCode } from './permissions';
export interface AuthorizationPolicy {
  permission: PermissionCode;
  action: string;
  entityType: string;
  states: readonly string[];
}
const policies: readonly AuthorizationPolicy[] = [
  ...(['DRAFT','SUBMITTED','UNDER_REVIEW','RETURNED','APPROVED','REJECTED','VOID'].flatMap((state) => [{ permission:'PERM-LAB-VIEW', action:'VIEW', entityType:'LAB_TEST', states:[state] }])) as unknown as AuthorizationPolicy[],
  { permission:'PERM-LAB-CREATE', action:'CREATE', entityType:'LAB_TEST', states:['DRAFT'] },
  { permission:'PERM-LAB-EDIT-DRAFT', action:'SAVE', entityType:'LAB_TEST', states:['DRAFT'] },
  { permission:'PERM-LAB-ENTER-SAMPLE', action:'SAVE', entityType:'LAB_TEST', states:['DRAFT'] },
  { permission:'PERM-LAB-ENTER-MEASUREMENT', action:'SAVE', entityType:'LAB_TEST', states:['DRAFT'] },
  { permission:'PERM-LAB-SUBMIT', action:'SUBMIT', entityType:'LAB_TEST', states:['DRAFT'] },
  { permission:'PERM-LAB-REVIEW', action:'REVIEW', entityType:'LAB_TEST', states:['SUBMITTED'] },
  { permission:'PERM-APR-REVIEW', action:'REVIEW', entityType:'LAB_TEST', states:['SUBMITTED'] },
  { permission:'PERM-LAB-RETURN', action:'RETURN', entityType:'LAB_TEST', states:['SUBMITTED','UNDER_REVIEW'] },
  { permission:'PERM-LAB-EDIT-DRAFT', action:'RESUME', entityType:'LAB_TEST', states:['RETURNED'] },
  { permission:'PERM-LAB-APPROVE', action:'APPROVE', entityType:'LAB_TEST', states:['UNDER_REVIEW'] },
  { permission:'PERM-APR-APPROVE', action:'APPROVE', entityType:'LAB_TEST', states:['UNDER_REVIEW'] },
  ...(['FINDING','NCR','RCA','CAPA'].flatMap((entityType) => [{ permission: `PERM-${entityType === 'FINDING' ? 'FIND' : entityType}-VIEW`, action: 'VIEW', entityType, states: ['DRAFT','OPEN','UNDER_REVIEW','UNDER_INVESTIGATION','RCA_IN_PROGRESS','CAPA_IN_PROGRESS','IN_PROGRESS','SUBMITTED','APPROVED','RETURNED','AWAITING_VERIFICATION','EFFECTIVENESS_REVIEW','READY_FOR_CLOSURE','CLOSED','VOID'] }])) as unknown as AuthorizationPolicy[],
  { permission: 'PERM-FIND-CREATE', action: 'CREATE', entityType: 'FINDING', states: ['DRAFT'] }, { permission: 'PERM-FIND-EDIT', action: 'EDIT', entityType: 'FINDING', states: ['DRAFT','OPEN'] }, { permission: 'PERM-FIND-REVIEW', action: 'SUBMIT_REVIEW', entityType: 'FINDING', states: ['OPEN'] }, { permission: 'PERM-FIND-REVIEW', action: 'RETURN', entityType: 'FINDING', states: ['UNDER_REVIEW'] }, { permission: 'PERM-FIND-CLOSE', action: 'CLOSE', entityType: 'FINDING', states: ['UNDER_REVIEW'] }, { permission: 'PERM-FIND-VOID', action: 'VOID', entityType: 'FINDING', states: ['DRAFT','OPEN','UNDER_REVIEW'] },
  { permission: 'PERM-NCR-CREATE', action: 'CREATE', entityType: 'NCR', states: ['DRAFT'] }, { permission: 'PERM-NCR-EDIT', action: 'START_INVESTIGATION', entityType: 'NCR', states: ['OPEN'] }, { permission: 'PERM-NCR-EDIT', action: 'START_RCA', entityType: 'NCR', states: ['UNDER_INVESTIGATION'] }, { permission: 'PERM-NCR-EDIT', action: 'MOVE_TO_CAPA', entityType: 'NCR', states: ['RCA_IN_PROGRESS'] }, { permission: 'PERM-NCR-EDIT', action: 'READY_FOR_CLOSURE', entityType: 'NCR', states: ['CAPA_IN_PROGRESS'] }, { permission: 'PERM-NCR-CLOSE', action: 'CLOSE', entityType: 'NCR', states: ['READY_FOR_CLOSURE'] },
  { permission: 'PERM-RCA-EDIT', action: 'START', entityType: 'RCA', states: ['DRAFT','RETURNED'] }, { permission: 'PERM-RCA-SUBMIT', action: 'SUBMIT', entityType: 'RCA', states: ['IN_PROGRESS'] }, { permission: 'PERM-RCA-REVIEW', action: 'RETURN', entityType: 'RCA', states: ['SUBMITTED'] }, { permission: 'PERM-RCA-APPROVE', action: 'APPROVE', entityType: 'RCA', states: ['SUBMITTED'] },
  { permission: 'PERM-CAPA-CREATE', action: 'CREATE', entityType: 'CAPA', states: ['DRAFT'] }, { permission: 'PERM-CAPA-EDIT', action: 'START', entityType: 'CAPA', states: ['OPEN'] }, { permission: 'PERM-CAPA-CLOSE', action: 'CLOSE', entityType: 'CAPA', states: ['READY_FOR_CLOSURE'] },
  { permission: 'PERM-TASK-VIEW', action: 'VIEW', entityType: 'TASK', states: ['DRAFT', 'OPEN', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED'] },
  { permission: 'PERM-TASK-CREATE', action: 'CREATE', entityType: 'TASK', states: ['DRAFT'] },
  { permission: 'PERM-TASK-CREATE', action: 'ACTIVATE', entityType: 'TASK', states: ['DRAFT'] },
  { permission: 'PERM-TASK-ASSIGN', action: 'ASSIGN', entityType: 'TASK', states: ['DRAFT', 'OPEN', 'IN_PROGRESS', 'ON_HOLD'] },
  { permission: 'PERM-TASK-EDIT', action: 'UPDATE_DRAFT', entityType: 'TASK', states: ['DRAFT'] },
  { permission: 'PERM-TASK-EDIT', action: 'START', entityType: 'TASK', states: ['OPEN'] },
  { permission: 'PERM-TASK-EDIT', action: 'RESUME', entityType: 'TASK', states: ['ON_HOLD'] },
  { permission: 'PERM-TASK-BLOCK', action: 'HOLD', entityType: 'TASK', states: ['OPEN', 'IN_PROGRESS'] },
  { permission: 'PERM-TASK-COMPLETE', action: 'COMPLETE', entityType: 'TASK', states: ['IN_PROGRESS'] },
  { permission: 'PERM-TASK-REOPEN', action: 'REOPEN', entityType: 'TASK', states: ['COMPLETED'] },
  ...(['RECEIVING_ITEM'].flatMap((entityType) => [{ permission:'PERM-QUAR-VIEW', action:'VIEW', entityType, states:['PENDING','READY_FOR_INSPECTION','UNDER_INSPECTION','INSPECTION_COMPLETE','RELEASE_PENDING','RELEASED','HOLD','EXPIRED','CANCELLED'] }, { permission:'PERM-QUAR-CREATE', action:'CREATE', entityType, states:['PENDING'] }, { permission:'PERM-QUAR-EDIT', action:'EDIT', entityType, states:['PENDING','READY_FOR_INSPECTION','UNDER_INSPECTION','INSPECTION_COMPLETE','RELEASE_PENDING','HOLD'] }, { permission:'PERM-QUAR-START-INSPECTION', action:'START_INSPECTION', entityType, states:['READY_FOR_INSPECTION'] }, { permission:'PERM-QUAR-HOLD', action:'HOLD', entityType, states:['PENDING','READY_FOR_INSPECTION','UNDER_INSPECTION','INSPECTION_COMPLETE','RELEASE_PENDING'] }])) as unknown as AuthorizationPolicy[],
  { permission:'PERM-QUAR-EDIT', action:'MARK_READY', entityType:'RECEIVING_ITEM', states:['PENDING'] }, { permission:'PERM-QUAR-EDIT', action:'COMPLETE_INSPECTION', entityType:'RECEIVING_ITEM', states:['UNDER_INSPECTION'] }, { permission:'PERM-QUAR-EDIT', action:'MOVE_TO_RELEASE_PENDING', entityType:'RECEIVING_ITEM', states:['INSPECTION_COMPLETE'] }, { permission:'PERM-QUAR-RELEASE', action:'RELEASE', entityType:'RECEIVING_ITEM', states:['RELEASE_PENDING'] },
  { permission:'PERM-INSP-CREATE', action:'CREATE', entityType:'INSPECTION_REPORT', states:['DRAFT'] }, { permission:'PERM-INSP-VIEW', action:'VIEW', entityType:'INSPECTION_REPORT', states:['DRAFT','SUBMITTED','UNDER_REVIEW','RETURNED','APPROVED','REJECTED','VOID'] }, { permission:'PERM-INSP-EDIT-DRAFT', action:'EDIT', entityType:'INSPECTION_REPORT', states:['DRAFT'] }, { permission:'PERM-INSP-EDIT-DRAFT', action:'RESUME', entityType:'INSPECTION_REPORT', states:['RETURNED'] }, { permission:'PERM-INSP-SUBMIT', action:'SUBMIT', entityType:'INSPECTION_REPORT', states:['DRAFT'] },
  { permission: 'PERM-IDN-VIEW-SELF', action: 'VIEW', entityType: 'ACCOUNT', states: ['ACTIVE'] },
  { permission: 'PERM-IDN-CHANGE-OWN-PASSWORD', action: 'CHANGE_PASSWORD', entityType: 'ACCOUNT', states: ['ACTIVE'] },
  { permission: 'PERM-IDN-MANAGE-USERS', action: 'MANAGE', entityType: 'USER', states: ['ACTIVE', 'INACTIVE', 'DISABLED'] },
  { permission: 'PERM-IDN-ACTIVATE', action: 'ACTIVATE', entityType: 'USER', states: ['INACTIVE', 'DISABLED'] },
  { permission: 'PERM-IDN-DEACTIVATE', action: 'DEACTIVATE', entityType: 'USER', states: ['ACTIVE', 'INACTIVE'] },
  { permission: 'PERM-IDN-RESET-PASSWORD', action: 'RESET_PASSWORD', entityType: 'USER', states: ['ACTIVE', 'INACTIVE', 'DISABLED'] },
  {
    permission: 'PERM-NOT-VIEW-OWN',
    action: 'VIEW',
    entityType: 'NOTIFICATION',
    states: ['ACTIVE'],
  },
  {
    permission: 'PERM-NOT-MARK-READ',
    action: 'MARK_READ',
    entityType: 'NOTIFICATION',
    states: ['ACTIVE'],
  },
  { permission: 'PERM-DASH-VIEW', action: 'VIEW', entityType: 'DASHBOARD', states: ['ACTIVE'] },
  { permission: 'PERM-DASH-MANAGEMENT', action: 'VIEW', entityType: 'DASHBOARD', states: ['ACTIVE'] },
  { permission: 'PERM-DASH-ADMIN', action: 'VIEW', entityType: 'DASHBOARD', states: ['ACTIVE'] },
  { permission: 'PERM-QUAR-VIEW', action: 'VIEW', entityType: 'QUARANTINE_DASHBOARD', states: ['ACTIVE'] },
  { permission: 'PERM-ADM-AUDIT-VIEW', action: 'VIEW', entityType: 'AUDIT_EVENT', states: ['ACTIVE'] },
  {
    permission: 'PERM-INSP-REVIEW',
    action: 'REVIEW',
    entityType: 'INSPECTION_REPORT',
    states: ['SUBMITTED', 'UNDER_REVIEW'],
  },
  { permission:'PERM-APR-REVIEW', action:'REVIEW', entityType:'INSPECTION_REPORT', states:['SUBMITTED','UNDER_REVIEW'] },
  { permission:'PERM-INSP-RETURN', action:'RETURN', entityType:'INSPECTION_REPORT', states:['SUBMITTED','UNDER_REVIEW'] },
  { permission:'PERM-APR-RETURN', action:'RETURN', entityType:'INSPECTION_REPORT', states:['SUBMITTED','UNDER_REVIEW'] },
  { permission:'PERM-INSP-APPROVE', action:'APPROVE', entityType:'INSPECTION_REPORT', states:['UNDER_REVIEW'] },
  { permission:'PERM-APR-APPROVE', action:'APPROVE', entityType:'INSPECTION_REPORT', states:['UNDER_REVIEW'] },
  { permission:'PERM-ADM-TEMPLATES', action:'VIEW', entityType:'QUARANTINE_ADMIN', states:['ACTIVE'] },
  { permission: 'PERM-ADM-ROLE-VIEW', action: 'VIEW', entityType: 'ROLE', states: ['ACTIVE'] },
  { permission: 'PERM-ADM-ROLE-ASSIGN', action: 'ASSIGN', entityType: 'ROLE', states: ['ACTIVE'] },
  { permission: 'PERM-ADM-PERMISSION-VIEW', action: 'VIEW', entityType: 'PERMISSION', states: ['ACTIVE'] },
  { permission: 'PERM-ADM-PERMISSION-ASSIGN', action: 'ASSIGN', entityType: 'ROLE', states: ['ACTIVE'] },
  { permission: 'PERM-ADM-SCOPE-ASSIGN', action: 'ASSIGN', entityType: 'USER', states: ['ACTIVE', 'INACTIVE', 'DISABLED'] },
  { permission: 'PERM-RPT-VIEW', action: 'VIEW', entityType: 'REPORT', states: ['ACTIVE'] },
  { permission: 'PERM-RPT-RUN', action: 'RUN', entityType: 'REPORT', states: ['ACTIVE'] },
  { permission: 'PERM-RPT-EXPORT', action: 'EXPORT', entityType: 'REPORT', states: ['ACTIVE'] },
  { permission: 'PERM-RPT-EXPORT-CSV', action: 'EXPORT', entityType: 'REPORT', states: ['ACTIVE'] },
  { permission: 'PERM-RPT-EXPORT-XLSX', action: 'EXPORT', entityType: 'REPORT', states: ['ACTIVE'] },
  { permission: 'PERM-EQP-VIEW', action: 'VIEW', entityType: 'EQUIPMENT', states: ['DRAFT','ACTIVE','OUT_OF_SERVICE','UNDER_MAINTENANCE','DECOMMISSIONED'] },
  { permission: 'PERM-EQP-CREATE', action: 'CREATE', entityType: 'EQUIPMENT', states: ['DRAFT'] },
  { permission: 'PERM-EQP-EDIT', action: 'EDIT', entityType: 'EQUIPMENT', states: ['DRAFT'] },
  { permission: 'PERM-EQP-CHANGE-STATUS', action: 'ACTIVATE', entityType: 'EQUIPMENT', states: ['DRAFT'] },
  { permission: 'PERM-EQP-CHANGE-STATUS', action: 'OUT_OF_SERVICE', entityType: 'EQUIPMENT', states: ['ACTIVE'] },
  { permission: 'PERM-EQP-CHANGE-STATUS', action: 'START_MAINTENANCE', entityType: 'EQUIPMENT', states: ['ACTIVE','OUT_OF_SERVICE'] },
  { permission: 'PERM-EQP-CHANGE-STATUS', action: 'RETURN_TO_SERVICE', entityType: 'EQUIPMENT', states: ['UNDER_MAINTENANCE','OUT_OF_SERVICE'] },
  { permission: 'PERM-EQP-DECOMMISSION', action: 'DECOMMISSION', entityType: 'EQUIPMENT', states: ['ACTIVE','OUT_OF_SERVICE','UNDER_MAINTENANCE'] },
  { permission: 'PERM-CAL-VIEW', action: 'VIEW', entityType: 'CALIBRATION_RECORD', states: ['DRAFT','SUBMITTED','APPROVED','CURRENT','DUE','OVERDUE','SUPERSEDED','VOID'] },
  { permission: 'PERM-CAL-CREATE', action: 'CREATE', entityType: 'CALIBRATION_RECORD', states: ['DRAFT'] },
  { permission: 'PERM-CAL-EDIT-DRAFT', action: 'EDIT', entityType: 'CALIBRATION_RECORD', states: ['DRAFT'] },
  { permission: 'PERM-CAL-SUBMIT', action: 'SUBMIT', entityType: 'CALIBRATION_RECORD', states: ['DRAFT'] },
  { permission: 'PERM-CAL-REVIEW', action: 'REVIEW', entityType: 'CALIBRATION_RECORD', states: ['SUBMITTED'] },
  { permission: 'PERM-CAL-APPROVE', action: 'APPROVE', entityType: 'CALIBRATION_RECORD', states: ['SUBMITTED'] },
  { permission: 'PERM-CAL-VOID', action: 'VOID', entityType: 'CALIBRATION_RECORD', states: ['DRAFT','SUBMITTED','APPROVED','CURRENT','DUE','OVERDUE'] },
  { permission: 'PERM-MNT-VIEW', action: 'VIEW', entityType: 'MAINTENANCE_RECORD', states: ['DRAFT','PLANNED','IN_PROGRESS','COMPLETED','CANCELLED','VOID'] },
  { permission: 'PERM-MNT-CREATE', action: 'CREATE', entityType: 'MAINTENANCE_RECORD', states: ['DRAFT'] },
  { permission: 'PERM-MNT-EDIT', action: 'PLAN', entityType: 'MAINTENANCE_RECORD', states: ['DRAFT'] },
  { permission: 'PERM-MNT-EDIT', action: 'START', entityType: 'MAINTENANCE_RECORD', states: ['PLANNED'] },
  { permission: 'PERM-MNT-EDIT', action: 'CANCEL', entityType: 'MAINTENANCE_RECORD', states: ['DRAFT','PLANNED'] },
  { permission: 'PERM-MNT-COMPLETE', action: 'COMPLETE', entityType: 'MAINTENANCE_RECORD', states: ['IN_PROGRESS'] },
  { permission: 'PERM-DOC-VIEW', action: 'VIEW', entityType: 'DOCUMENT_IDENTITY', states: ['CATALOG_ONLY'] },
  { permission: 'PERM-DOC-CREATE', action: 'CREATE', entityType: 'DOCUMENT_IDENTITY', states: ['CATALOG_ONLY'] },
  ...(['CATALOG_ONLY','DRAFT','IN_REVIEW','RETURNED','APPROVED','EFFECTIVE','SUPERSEDED','ARCHIVED','VOID'].flatMap((state) => [{ permission: 'PERM-DOC-VIEW', action: 'VIEW', entityType: 'DOCUMENT_VERSION', states: [state] }, { permission: 'PERM-DOC-DOWNLOAD', action: 'DOWNLOAD', entityType: 'DOCUMENT_VERSION', states: [state] }])) as unknown as AuthorizationPolicy[],
  { permission: 'PERM-DOC-EDIT-DRAFT', action: 'EDIT', entityType: 'DOCUMENT_VERSION', states: ['DRAFT'] },
  { permission: 'PERM-DOC-SUBMIT', action: 'SUBMIT', entityType: 'DOCUMENT_VERSION', states: ['DRAFT'] },
  { permission: 'PERM-DOC-REVIEW', action: 'REVIEW', entityType: 'DOCUMENT_VERSION', states: ['IN_REVIEW'] },
  { permission: 'PERM-APR-REVIEW', action: 'REVIEW', entityType: 'DOCUMENT_VERSION', states: ['IN_REVIEW'] },
  { permission: 'PERM-DOC-APPROVE', action: 'APPROVE', entityType: 'DOCUMENT_VERSION', states: ['IN_REVIEW'] },
  { permission: 'PERM-APR-APPROVE', action: 'APPROVE', entityType: 'DOCUMENT_VERSION', states: ['IN_REVIEW'] },
  { permission: 'PERM-DOC-REVISE', action: 'REVISE', entityType: 'DOCUMENT_IDENTITY', states: ['APPROVED','EFFECTIVE','SUPERSEDED'] },
  { permission: 'PERM-DOC-SUPERSEDE', action: 'SUPERSEDE', entityType: 'DOCUMENT_VERSION', states: ['EFFECTIVE','APPROVED'] },
  {
    permission: 'PERM-APR-VIEW-ASSIGNED',
    action: 'VIEW',
    entityType: 'APPROVAL_WORK_ITEM',
    states: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'RETURNED', 'CANCELLED', 'EXPIRED'],
  },
  {
    permission: 'PERM-APR-REVIEW',
    action: 'REVIEW',
    entityType: 'APPROVAL_WORK_ITEM',
    states: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'RETURNED', 'CANCELLED', 'EXPIRED'],
  },
  {
    permission: 'PERM-APR-RETURN',
    action: 'RETURN',
    entityType: 'APPROVAL_WORK_ITEM',
    states: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'RETURNED', 'CANCELLED', 'EXPIRED'],
  },
  {
    permission: 'PERM-APR-APPROVE',
    action: 'APPROVE',
    entityType: 'APPROVAL_WORK_ITEM',
    states: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'RETURNED', 'CANCELLED', 'EXPIRED'],
  },
  {
    permission: 'PERM-APR-REJECT',
    action: 'REJECT',
    entityType: 'APPROVAL_WORK_ITEM',
    states: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'RETURNED', 'CANCELLED', 'EXPIRED'],
  },
  {
    permission: 'PERM-APR-VIEW-HISTORY',
    action: 'VIEW_HISTORY',
    entityType: 'APPROVAL_CASE',
    states: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'RETURNED', 'CANCELLED', 'EXPIRED'],
  },
  { permission: 'PERM-CHG-VIEW', action: 'VIEW', entityType: 'CHANGE_REQUEST', states: ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'RETURNED', 'APPROVED', 'REJECTED', 'APPLYING', 'APPLIED', 'APPLICATION_FAILED', 'CANCELLED'] },
  { permission: 'PERM-CHG-CREATE', action: 'CREATE', entityType: 'CHANGE_REQUEST', states: ['DRAFT'] },
  { permission: 'PERM-CHG-EDIT-DRAFT', action: 'RESUME', entityType: 'CHANGE_REQUEST', states: ['RETURNED'] },
  { permission: 'PERM-CHG-SUBMIT', action: 'SUBMIT', entityType: 'CHANGE_REQUEST', states: ['DRAFT'] },
  { permission: 'PERM-CHG-REVIEW', action: 'REVIEW', entityType: 'CHANGE_REQUEST', states: ['SUBMITTED'] },
  { permission: 'PERM-CHG-RETURN', action: 'RETURN', entityType: 'CHANGE_REQUEST', states: ['UNDER_REVIEW'] },
  { permission: 'PERM-CHG-APPROVE', action: 'APPROVE', entityType: 'CHANGE_REQUEST', states: ['UNDER_REVIEW'] },
  { permission: 'PERM-CHG-REJECT', action: 'REJECT', entityType: 'CHANGE_REQUEST', states: ['UNDER_REVIEW'] },
  { permission: 'PERM-CHG-CANCEL', action: 'CANCEL', entityType: 'CHANGE_REQUEST', states: ['DRAFT', 'RETURNED'] },
  ...([
    'INSPECTION_REPORT',
    'LAB_TEST',
    'DOCUMENT_VERSION',
    'CALIBRATION_RECORD',
    'CAPA',
    'CHANGE_REQUEST',
    'RCA',
    'NCR',
    'FINDING',
  ].flatMap((entityType) => [
    {
      permission: 'PERM-APR-REVIEW',
      action: 'REVIEW',
      entityType,
      states: ['SUBMITTED', 'UNDER_REVIEW', 'IN_REVIEW'],
    },
    {
      permission: 'PERM-ESIG-SIGN',
      action: 'SIGN',
      entityType,
      states: [
        'DRAFT',
        'SUBMITTED',
        'UNDER_REVIEW',
        'IN_REVIEW',
        'RETURNED',
        'APPROVED',
        'REJECTED',
        'OPEN',
        'IN_PROGRESS',
        'CLOSED',
        'READY_FOR_CLOSURE',
      ],
    },
  ]) as unknown as AuthorizationPolicy[]),
  ...([
    'INSPECTION_REPORT',
    'LAB_TEST',
    'DOCUMENT_VERSION',
    'CALIBRATION_RECORD',
    'CAPA',
    'CHANGE_REQUEST',
    'RCA',
    'NCR',
    'FINDING',
  ].flatMap((entityType) => [
    {
      permission: 'PERM-APR-APPROVE',
      action: 'APPROVE',
      entityType,
      states: ['SUBMITTED', 'UNDER_REVIEW', 'IN_REVIEW', 'READY_FOR_CLOSURE'],
    },
    {
      permission: 'PERM-APR-RETURN',
      action: 'RETURN',
      entityType,
      states: ['SUBMITTED', 'UNDER_REVIEW', 'IN_REVIEW'],
    },
    {
      permission: 'PERM-APR-REJECT',
      action: 'REJECT',
      entityType,
      states: ['SUBMITTED', 'UNDER_REVIEW', 'IN_REVIEW'],
    },
  ]) as unknown as AuthorizationPolicy[]),
];
export function getAuthorizationPolicy(
  permission: PermissionCode,
  action: string,
  entityType: string,
): AuthorizationPolicy | undefined {
  return policies.find(
    (p) => p.permission === permission && p.action === action && p.entityType === entityType,
  );
}
