export {
  UAT_ACCEPTANCE_OUTCOMES,
  UAT_ASSISTANCE,
  UAT_DEFECT_SEVERITIES,
  UAT_DEFECT_STATUSES,
  UAT_ENVIRONMENTS,
  UAT_PARTICIPANT_ROLES,
  UAT_SCENARIO_STATUSES,
  UAT_SEVERITIES,
  UAT_TASK_ACCEPT_REJECT,
} from '../domain/uat-evidence.js';
