import type { Kysely, Transaction } from 'kysely';
import { sql } from 'kysely';
import type { DatabaseSchema, DatabaseRow } from '../../../../shared/database/db-types.js';
import { translateDatabaseError } from '../../../../shared/database/database.js';
import { AppError } from '../../../../shared/errors/app-error.js';
import { isUuid } from '../../../../shared/id/uuid.js';
import { actorHasScope } from '../../../../shared/authorization/scope-evaluator.js';
import type { ActorContext } from '../../../../shared/authorization/types.js';
import type { AuditRepository } from '../../../../shared/audit/audit-repository.js';
import { PostgresAuditRepository } from '../../../../shared/audit/postgres-audit-repository.js';
import type { OutboxRepository } from '../../../../shared/outbox/outbox-repository.js';
import { PostgresOutboxRepository } from '../../../../shared/outbox/postgres-outbox-repository.js';
import { transitionCalibration, type CalibrationAction, type CalibrationRecord } from '../domain/calibration.js';
import type { CalibrationListFilter, CalibrationRepository } from '../ports/repository.js';

const map = (row: DatabaseRow<'calibration_records'>): CalibrationRecord => ({ id: row.id, calibrationNo: row.calibration_no, equipmentId: row.equipment_id, state: row.state as CalibrationRecord['state'], calibrationDate: new Date(`${row.calibration_date}T00:00:00.000Z`), dueDate: row.due_date ? new Date(`${row.due_date}T00:00:00.000Z`) : undefined, provider: row.provider ?? undefined, certificateNo: row.certificate_no ?? undefined, result: row.result ?? undefined, approvedAt: row.approved_at ?? undefined, approvedBy: row.approved_by ?? undefined, becameCurrentAt: row.became_current_at ?? undefined, supersededAt: row.superseded_at ?? undefined, voidedAt: row.voided_at ?? undefined, voidReason: row.void_reason ?? undefined, createdAt: row.created_at, createdBy: row.created_by, updatedAt: row.updated_at, version: BigInt(row.version) });
const entity = (x: CalibrationRecord) => ({ type: 'CALIBRATION_RECORD', id: x.id, state: x.state, ownerId: x.createdBy });
export class PostgresCalibrationRepository implements CalibrationRepository {
  constructor(private readonly db: Kysely<DatabaseSchema>, private readonly audit?: AuditRepository, private readonly outbox?: OutboxRepository) {}
  async create(input: { calibration: CalibrationRecord; actor: ActorContext; requestId: string }): Promise<CalibrationRecord> { try { const x = input.calibration; return await this.db.transaction().execute(async (tx) => { const row = await tx.insertInto('calibration_records').values({ id: x.id, calibration_no: x.calibrationNo, equipment_id: x.equipmentId, state: 'DRAFT', calibration_date: x.calibrationDate.toISOString().slice(0, 10), due_date: x.dueDate?.toISOString().slice(0, 10) ?? null, provider: x.provider ?? null, certificate_no: x.certificateNo ?? null, result: x.result ?? null, approved_at: null, approved_by: null, became_current_at: null, superseded_at: null, voided_at: null, void_reason: null, created_by: input.actor.id, updated_at: x.updatedAt, version: 1n }).returningAll().executeTakeFirstOrThrow(); await this.auditFor(tx)?.append({ actorType: 'USER', actorId: input.actor.id, subjectType: 'CALIBRATION_RECORD', subjectId: x.id, action: 'CREATE_CALIBRATION', newState: 'DRAFT', requestId: input.requestId }); await this.outboxFor(tx)?.enqueue({ eventType: 'CALIBRATION_CREATED', aggregateType: 'CALIBRATION_RECORD', aggregateId: x.id, payload: { calibrationNo: x.calibrationNo, equipmentId: x.equipmentId, state: 'DRAFT' }, dedupeKey: `calibration-created:${x.id}` }); return map(row); }); } catch (error) { throw translateDatabaseError(error); } }
  async get(id: string, actor: ActorContext): Promise<CalibrationRecord | undefined> { if (!isUuid(id)) return undefined; const row = await this.db.selectFrom('calibration_records').selectAll().where('id', '=', id).executeTakeFirst(); if (!row) return undefined; const x = map(row); const grant = actor.permissions.find((p) => p.code === 'PERM-CAL-VIEW'); return actorHasScope(actor, entity(x), { ownerId: x.createdBy }, grant) ? x : undefined; }
  async list(input: { actor: ActorContext; filter?: CalibrationListFilter }): Promise<readonly CalibrationRecord[]> { let query = this.db.selectFrom('calibration_records').selectAll().orderBy('updated_at', 'desc'); if (input.filter?.state) query = query.where('state', '=', input.filter.state) as typeof query; if (input.filter?.equipmentId) query = query.where('equipment_id', '=', input.filter.equipmentId) as typeof query; if (input.filter?.search) query = query.where('calibration_no', 'ilike', `%${input.filter.search}%`) as typeof query; const rows = await query.execute(); const grant = input.actor.permissions.find((p) => p.code === 'PERM-CAL-VIEW'); return rows.map(map).filter((x) => actorHasScope(input.actor, entity(x), { ownerId: x.createdBy }, grant)); }
  async transition(input: { id: string; expectedVersion: bigint; actor: ActorContext; action: CalibrationAction; reason?: string; requestId: string }): Promise<CalibrationRecord> { try { const old = await this.get(input.id, input.actor); if (!old) throw new AppError('RESOURCE_NOT_FOUND', { userSafe: true }); const changed = transitionCalibration(old, input.action, new Date(), input.reason); return await this.db.transaction().execute(async (tx) => { if (input.action === 'MAKE_CURRENT') { await tx.updateTable('calibration_records').set({ state: 'SUPERSEDED', superseded_at: new Date(), updated_at: new Date(), version: sql<bigint>`version + 1` }).where('equipment_id', '=', old.equipmentId).where('id', '!=', old.id).where('state', 'in', ['CURRENT', 'DUE', 'OVERDUE']).execute(); await tx.updateTable('equipment').set({ current_calibration_id: old.id, updated_at: new Date(), version: sql<bigint>`version + 1` }).where('id', '=', old.equipmentId).execute(); }
      const row = await tx.updateTable('calibration_records').set({ state: changed.state, approved_at: changed.approvedAt ?? null, approved_by: input.action === 'APPROVE' ? input.actor.id : old.approvedBy ?? null, became_current_at: changed.becameCurrentAt ?? null, superseded_at: changed.supersededAt ?? null, voided_at: changed.voidedAt ?? null, void_reason: changed.voidReason ?? null, updated_at: changed.updatedAt, version: input.expectedVersion + 1n }).where('id', '=', input.id).where('state', '=', old.state).where('version', '=', input.expectedVersion).returningAll().executeTakeFirst(); if (!row) throw new AppError('CONFLICT_STALE_VERSION', { userSafe: true }); await this.auditFor(tx)?.append({ actorType: 'USER', actorId: input.actor.id, subjectType: 'CALIBRATION_RECORD', subjectId: input.id, action: input.action, oldState: old.state, newState: changed.state, reason: input.reason, requestId: input.requestId }); await this.outboxFor(tx)?.enqueue({ eventType: 'CALIBRATION_CHANGED', aggregateType: 'CALIBRATION_RECORD', aggregateId: input.id, payload: { action: input.action, state: changed.state }, dedupeKey: `calibration:${input.id}:v${changed.version}` }); return map(row); }); } catch (error) { if (error instanceof AppError) throw error; throw translateDatabaseError(error); } }
  private auditFor(tx: Transaction<DatabaseSchema>): AuditRepository | undefined { return this.audit instanceof PostgresAuditRepository ? new PostgresAuditRepository(tx) : this.audit; }
  private outboxFor(tx: Transaction<DatabaseSchema>): OutboxRepository | undefined { return this.outbox instanceof PostgresOutboxRepository ? new PostgresOutboxRepository(tx) : this.outbox; }
}
