import { describe, expect, it } from 'vitest';
import { ExportReportUseCase } from '../../../src/modules/reporting/application/export-report.js';
import { ReportRegistry } from '../../../src/modules/reporting/application/report-registry.js';
import type { ActorContext } from '../../../src/shared/authorization/types.js';
import type { ReportQuery } from '../../../src/modules/reporting/ports/report-query.js';

const actor = (
  permissions: ActorContext['permissions'] = [
    { code: 'PERM-RPT-VIEW', scopes: ['OWN'] },
    { code: 'PERM-RPT-RUN', scopes: ['OWN'] },
    { code: 'PERM-RPT-EXPORT', scopes: ['OWN'] },
    { code: 'PERM-RPT-EXPORT-CSV', scopes: ['OWN'] },
    { code: 'PERM-RPT-EXPORT-XLSX', scopes: ['OWN'] },
  ],
): ActorContext => ({
  id: 'user-1',
  loginIdentity: 'report-user-1',
  accountState: 'ACTIVE',
  roles: ['Employee'],
  permissions,
});

const query: ReportQuery = {
  run: async (definition, currentActor: ActorContext) => ({
    definition,
    columns: definition.columns,
    rows: [{ receivingNo: '=formula', createdBy: currentActor.id }],
  }),
};

describe('authorized report exports', () => {
  it('uses the same canonical rows for CSV and XLSX and neutralizes formulas', async () => {
    const useCase = new ExportReportUseCase(
      new ReportRegistry(),
      query,
      () => new Date('2026-09-23T12:00:00.000Z'),
    );
    const csv = await useCase.execute(actor(), 'quarantine-aging', 'CSV', {});
    const xlsx = await useCase.execute(actor(), 'quarantine-aging', 'XLSX', {});
    expect(csv.bytes.toString('utf8')).toContain("'=formula");
    expect(csv.bytes.toString('utf8')).toContain('UNAPPROVED REPORT COPY');
    expect(csv.bytes.toString('utf8')).toContain('2026-09-23T12:00:00.000Z');
    expect(csv.bytes.toString('utf8')).toContain('Generated by,report-user-1');
    expect(csv.bytes.toString('utf8')).toContain('Record count,1 records');
    expect(csv.bytes.toString('utf8')).toContain('Filters,No optional filters');
    expect(xlsx.mimeType).toContain('spreadsheetml');
    expect(xlsx.bytes.subarray(0, 2).toString()).toBe('PK');
    expect(xlsx.bytes.toString('utf8')).toContain('Actor scope');
    expect(xlsx.bytes.toString('utf8')).toContain('qc.receiving_items');
  });

  it('reauthorizes export independently from report viewing', async () => {
    const useCase = new ExportReportUseCase(new ReportRegistry(), query);
    await expect(
      useCase.execute(
        actor([
          { code: 'PERM-RPT-VIEW', scopes: ['OWN'] },
          { code: 'PERM-RPT-RUN', scopes: ['OWN'] },
          { code: 'PERM-RPT-EXPORT', scopes: ['OWN'] },
        ]),
        'quarantine-aging',
        'CSV',
        {},
      ),
    ).rejects.toMatchObject({ code: 'AUTHZ_PERMISSION_MISSING' });
  });
});
